"use client";

import { Badge, Button, EmptyState, SaveStatus, SelectField, Skeleton, Switch, TextField, Toast } from "@/ui";
export default function TokensPage() {
  return <main className="app-shell py-16"><p className="text-sm font-bold uppercase tracking-[0.16em] text-app-accent">Referência interna</p><h1 className="mt-2 text-4xl font-bold tracking-tight">Tokens e estados</h1><p className="mt-3 max-w-2xl text-app-muted">App chrome e tema da página são camadas independentes. Esta rota reúne os estados que precisam ser conferidos visualmente.</p>
    <div className="mt-10 grid gap-6 lg:grid-cols-2">
      <section className="surface-card p-6"><h2 className="text-2xl font-bold">Cores semânticas</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{[["Texto","var(--app-text)"],["Superfície","var(--app-surface)"],["Acento","var(--app-accent)"],["Sucesso","var(--app-success)"],["Aviso","var(--app-warning)"],["Perigo","var(--app-danger)"]].map(([name,color]) => <div key={name} className="rounded-xl border border-app-border p-3"><span className="mb-2 block h-12 rounded-lg" style={{ background: color }} /><b>{name}</b></div>)}</div></section>
      <section className="surface-card p-6"><h2 className="text-2xl font-bold">Botões</h2><div className="mt-5 flex flex-wrap gap-3"><Button>Primário</Button><Button variant="secondary">Secundário</Button><Button variant="ghost">Fantasma</Button><Button variant="danger">Perigo</Button><Button disabled>Desativado</Button><Button loading>Carregando</Button></div></section>
      <section className="surface-card p-6"><h2 className="text-2xl font-bold">Campos e controles</h2><div className="mt-5 grid gap-5"><TextField id="token-field" label="Nome da página" hint="Como visitantes verão." defaultValue="Café Ipê" /><TextField id="token-error" label="Endereço" error="Este endereço está em uso. Tente acrescentar sua cidade." defaultValue="cafe" /><SelectField id="token-select" label="Período" defaultValue="7"><option value="7">7 dias</option><option value="30">30 dias</option></SelectField><Switch checked label="Bloco visível" onChange={() => undefined} /></div></section>
      <section className="surface-card p-6"><h2 className="text-2xl font-bold">Feedback</h2><div className="mt-5 flex flex-wrap gap-3"><Badge>Rascunho</Badge><Badge tone="success">Publicado</Badge><Badge tone="warning">Pendente</Badge><Badge tone="danger">Erro</Badge></div><div className="mt-5 grid gap-2"><SaveStatus state="saving" /><SaveStatus state="saved" /><SaveStatus state="error" /></div></section>
      <section className="surface-card p-6"><h2 className="text-2xl font-bold">Vazio e carregamento</h2><div className="mt-5 grid gap-5"><EmptyState title="Nenhuma página ainda" description="Crie sua primeira página para começar." action={<Button>Criar página</Button>} /><Skeleton height={22} /><Skeleton height={80} /></div></section>
      <section className="surface-card overflow-hidden p-6"><h2 className="text-2xl font-bold">Tema da página</h2><div className="bio-theme mt-5 rounded-2xl p-6 text-center"><h3 className="font-[family-name:var(--page-heading-font)] text-2xl font-bold">Café Ipê</h3><p className="mt-2 text-[var(--page-muted)]">Café e encontros no centro.</p><a className="bio-button mt-5" href="#tema">Falar no WhatsApp</a></div></section>
    </div><Toast actionLabel="Desfazer" onAction={() => undefined}>Bloco excluído.</Toast></main>;
}
