// User-facing vocabulary lives here so usability findings (UX-001..UX-003 are still provisional)
// change copy without touching the schema, which keeps neutral terms (workspace, profile, membership).
export const COPY = {
  genericError: "Algo não saiu como esperado. Tente novamente.",
  loading: "Carregando…",
  save: { idle: "Alterações não publicadas", saving: "Salvando…", saved: "Salvo", error: "Não foi possível salvar — tentar novamente" },
  publish: { publishing: "Publicando sua página…", published: "Página publicada", error: "Não foi possível publicar. Revise sua conexão e tente novamente." },
  analytics: { noData: "Sem dados ainda — compartilhe seu link para começar.", zero: "Nenhuma visita neste período." },
  report: { expired: "Este relatório expirou. Peça um novo link à agência.", revoked: "Este relatório não está mais disponível. Fale com a agência." },
} as const;

export const AUTH_COPY = {
  validation: {
    name: "Informe como você quer ser chamado (2 a 80 caracteres).",
    email: "Digite um e-mail válido.",
    passwordRequired: "Digite sua senha.",
    passwordTooShort: "Use pelo menos 8 caracteres.",
    passwordTooLong: "Use no máximo 72 caracteres.",
    passwordLettersDigits: "Use letras e números na senha.",
    passwordMismatch: "As senhas não coincidem.",
    summary: "Revise os campos indicados e tente novamente.",
  },
  passwordHint: "Pelo menos 8 caracteres, com letras e números.",
  signUp: {
    title: "Crie seu acesso",
    lead: "Sua página no ar em poucos minutos. Você confirma o e-mail antes de começar.",
    submit: "Criar acesso",
    haveAccount: "Já tem acesso?",
    signInLink: "Entrar",
    // Same text whether the email is new or already registered (anti-enumeration).
    checkEmailTitle: "Confira seu e-mail",
    checkEmail: "Se este e-mail puder ser usado, enviamos um link de confirmação. Ele expira em 1 hora. Confira também a caixa de spam.",
  },
  signIn: {
    title: "Entrar",
    lead: "Acesse suas páginas e resultados.",
    submit: "Entrar",
    forgot: "Esqueci minha senha",
    noAccount: "Ainda não tem acesso?",
    signUpLink: "Criar acesso",
    invalidCredentials: "E-mail ou senha incorretos.",
    emailNotConfirmed: "Confirme seu e-mail para entrar. Se o link expirou, peça um novo abaixo.",
    signedOut: "Você saiu da sua conta.",
    passwordUpdated: "Senha atualizada. Entre com a nova senha.",
  },
  confirmEmail: {
    title: "Confirme seu e-mail",
    lead: "Abra o link que enviamos para ativar seu acesso. Não chegou? Peça outro envio.",
    submit: "Reenviar link de confirmação",
    sent: "Se houver um cadastro pendente para este e-mail, enviamos um novo link. Ele expira em 1 hora.",
  },
  recovery: {
    title: "Recuperar acesso",
    lead: "Informe o e-mail da sua conta. Enviaremos um link para criar uma nova senha.",
    submit: "Enviar link",
    // Same text whether or not the email exists (anti-enumeration).
    sent: "Se existir uma conta com este e-mail, enviamos um link para redefinir a senha. Ele expira em 1 hora.",
    backToSignIn: "Voltar para entrar",
  },
  resetPassword: {
    title: "Crie uma nova senha",
    lead: "Escolha uma senha que você não usa em outros serviços.",
    submit: "Salvar nova senha",
    samePassword: "A nova senha precisa ser diferente da atual.",
    sessionExpired: "Seu link de recuperação expirou ou já foi usado. Peça um novo para continuar.",
  },
  link: {
    expiredTitle: "Link expirado ou inválido",
    expired: "Este link expirou ou já foi usado. Peça um novo para continuar.",
    requestNewConfirmation: "Pedir novo link de confirmação",
    requestNewRecovery: "Pedir novo link de recuperação",
  },
  rateLimited: "Muitas tentativas em pouco tempo. Aguarde alguns minutos e tente novamente.",
  unavailable: "Não foi possível falar com o serviço de acesso agora. Tente novamente em instantes.",
  signOut: "Sair",
  fields: { name: "Seu nome", email: "E-mail", password: "Senha", newPassword: "Nova senha", confirmation: "Repita a nova senha" },
} as const;

export const APP_COPY = {
  workspace: {
    personalLabel: "Pessoal",
    agencyLabel: "Conta da agência",
    switcherLabel: "Você está em",
    createAgency: "Criar conta da agência",
    createAgencyTitle: "Nova conta da agência",
    createAgencyLead: "Use uma conta separada para as páginas dos seus clientes. Você será o proprietário.",
    agencyNameLabel: "Nome da agência",
    agencyNameError: "Use de 2 a 80 caracteres.",
    agencyLimit: "Você já tem o máximo de 3 contas de agência ativas.",
    notFoundTitle: "Conta não encontrada",
    notFound: "Esta conta não existe ou você não tem acesso a ela.",
    preparingError: "Não foi possível preparar sua conta. Tente novamente.",
    retry: "Tentar novamente",
  },
  roles: { owner: "Proprietário", admin: "Administrador", editor: "Editor" },
  pages: {
    listTitle: "Páginas",
    usage: (used: number, limit: number) => `${used} de ${limit} ${limit === 1 ? "página" : "páginas"}`,
    create: "Nova página",
    emptyTitle: "Você ainda não criou nenhuma página.",
    emptyDescription: "Crie sua primeira página para escolher o endereço e começar a montar o conteúdo.",
    limitReached: (limit: number) => `Esta conta já usa ${limit === 1 ? "sua página disponível" : `as ${limit} páginas disponíveis`} no plano atual. Para criar outra, exclua uma página existente.`,
    createForbidden: "Somente proprietários e administradores criam páginas nesta conta.",
    status: { draft: "Rascunho", published: "Publicada", archived: "Arquivada" },
    settings: "Configurações",
    publicAddressPrefix: "projeto.test/",
    notFoundTitle: "Página não encontrada",
    notFound: "Esta página não existe, foi excluída ou você não tem acesso a ela.",
  },
  onboarding: {
    eyebrow: "Primeiros passos",
    title: "Crie sua primeira página",
    lead: "Comece pelo básico. Você poderá editar tudo depois.",
    submit: "Criar página",
    skip: "Fazer isso depois",
  },
  profileForm: {
    title: "Nome da página",
    titleHint: "Aparece no topo da página. Ex.: Café Ipê ou Ana Lima — Nutrição.",
    titleError: "Informe um nome de 1 a 80 caracteres.",
    slug: "Endereço da página",
    slugHint: "Letras, números e hífens. Acentos e espaços são ajustados automaticamente.",
    checking: "Verificando disponibilidade…",
    bio: "Apresentação (opcional)",
    bioHint: (remaining: number) => `Até 280 caracteres. Restam ${remaining}.`,
    bioError: "Use no máximo 280 caracteres.",
    avatar: "Foto ou logo",
    avatarPlaceholder: "O envio de imagem chega em breve. Por enquanto, mostramos suas iniciais.",
    created: "Página criada como rascunho.",
    saved: "Alterações salvas.",
    save: "Salvar alterações",
  },
  slugChange: {
    open: "Alterar endereço",
    title: "Alterar endereço da página",
    warning: "O endereço atual deixará de funcionar. Quem tiver o link antigo não encontrará sua página. O endereço antigo fica protegido para esta conta por 90 dias.",
    confirm: "Alterar endereço",
    cancel: "Cancelar",
    changed: (slug: string) => `Endereço alterado para ${slug}.`,
    forbidden: "Somente proprietários e administradores alteram o endereço.",
  },
  deletePage: {
    open: "Excluir página",
    title: "Excluir esta página?",
    warning: "A página sai da sua lista e o endereço deixa de funcionar. Os dados ficam guardados por 30 dias para recuperação pelo suporte e depois são apagados.",
    confirm: "Excluir página",
    cancel: "Cancelar",
    deleted: "Página excluída.",
    forbidden: "Somente proprietários e administradores excluem páginas.",
  },
  errors: {
    forbidden: "Você não tem permissão para fazer isso nesta conta.",
    notFound: "Não encontramos este item ou você não tem acesso a ele.",
    unavailable: "Não foi possível concluir agora. Tente novamente em instantes.",
    sessionExpired: "Sua sessão expirou. Entre novamente para continuar.",
  },
  nav: { home: "Início", skipToContent: "Pular para o conteúdo" },
} as const;
