// User-facing vocabulary lives here so usability findings (UX-001..UX-003 are still provisional)
// change copy without touching the schema, which keeps neutral terms (workspace, profile, membership).
export const COPY = {
  genericError: "Algo não saiu como esperado. Tente novamente.",
  loading: "Carregando…",
  save: { idle: "Alterações não publicadas", saving: "Salvando…", saved: "Salvo", error: "Não foi possível salvar — tentar novamente" },
  publish: { publishing: "Publicando sua página…", published: "Página publicada", error: "Não foi possível publicar. Revise sua conexão e tente novamente." },
  analytics: { noData: "Sem dados ainda — compartilhe seu link para começar.", zero: "Nenhuma visita neste período." },
  report: { expired: "Este relatório expirou. Peça um novo link à agência.", revoked: "Este relatório não está mais disponível. Fale com a agência." },
} as const;

export const AUTH_COPY = {
  validation: {
    name: "Informe como você quer ser chamado (2 a 80 caracteres).",
    email: "Digite um e-mail válido.",
    passwordRequired: "Digite sua senha.",
    passwordTooShort: "Use pelo menos 8 caracteres.",
    passwordTooLong: "Use no máximo 72 caracteres.",
    passwordLettersDigits: "Use letras e números na senha.",
    passwordMismatch: "As senhas não coincidem.",
    summary: "Revise os campos indicados e tente novamente.",
  },
  passwordHint: "Pelo menos 8 caracteres, com letras e números.",
  signUp: {
    title: "Crie seu acesso",
    lead: "Sua página no ar em poucos minutos. Você confirma o e-mail antes de começar.",
    submit: "Criar acesso",
    haveAccount: "Já tem acesso?",
    signInLink: "Entrar",
    // Same text whether the email is new or already registered (anti-enumeration).
    checkEmailTitle: "Confira seu e-mail",
    checkEmail: "Se este e-mail puder ser usado, enviamos um link de confirmação. Ele expira em 1 hora. Confira também a caixa de spam.",
  },
  signIn: {
    title: "Entrar",
    lead: "Acesse suas páginas e resultados.",
    submit: "Entrar",
    forgot: "Esqueci minha senha",
    noAccount: "Ainda não tem acesso?",
    signUpLink: "Criar acesso",
    invalidCredentials: "E-mail ou senha incorretos.",
    emailNotConfirmed: "Confirme seu e-mail para entrar. Se o link expirou, peça um novo abaixo.",
    signedOut: "Você saiu da sua conta.",
    passwordUpdated: "Senha atualizada. Entre com a nova senha.",
  },
  confirmEmail: {
    title: "Confirme seu e-mail",
    lead: "Abra o link que enviamos para ativar seu acesso. Não chegou? Peça outro envio.",
    submit: "Reenviar link de confirmação",
    sent: "Se houver um cadastro pendente para este e-mail, enviamos um novo link. Ele expira em 1 hora.",
  },
  recovery: {
    title: "Recuperar acesso",
    lead: "Informe o e-mail da sua conta. Enviaremos um link para criar uma nova senha.",
    submit: "Enviar link",
    // Same text whether or not the email exists (anti-enumeration).
    sent: "Se existir uma conta com este e-mail, enviamos um link para redefinir a senha. Ele expira em 1 hora.",
    backToSignIn: "Voltar para entrar",
  },
  resetPassword: {
    title: "Crie uma nova senha",
    lead: "Escolha uma senha que você não usa em outros serviços.",
    submit: "Salvar nova senha",
    samePassword: "A nova senha precisa ser diferente da atual.",
    sessionExpired: "Seu link de recuperação expirou ou já foi usado. Peça um novo para continuar.",
  },
  link: {
    expiredTitle: "Link expirado ou inválido",
    expired: "Este link expirou ou já foi usado. Peça um novo para continuar.",
    requestNewConfirmation: "Pedir novo link de confirmação",
    requestNewRecovery: "Pedir novo link de recuperação",
  },
  rateLimited: "Muitas tentativas em pouco tempo. Aguarde alguns minutos e tente novamente.",
  unavailable: "Não foi possível falar com o serviço de acesso agora. Tente novamente em instantes.",
  signOut: "Sair",
  fields: { name: "Seu nome", email: "E-mail", password: "Senha", newPassword: "Nova senha", confirmation: "Repita a nova senha" },
} as const;

export const APP_COPY = {
  workspace: {
    personalLabel: "Pessoal",
    agencyLabel: "Conta da agência",
    switcherLabel: "Você está em",
    createAgency: "Criar conta da agência",
    createAgencyTitle: "Nova conta da agência",
    createAgencyLead: "Use uma conta separada para as páginas dos seus clientes. Você será o proprietário.",
    agencyNameLabel: "Nome da agência",
    agencyNameError: "Use de 2 a 80 caracteres.",
    agencyLimit: "Você já tem o máximo de 3 contas de agência ativas.",
    notFoundTitle: "Conta não encontrada",
    notFound: "Esta conta não existe ou você não tem acesso a ela.",
    preparingError: "Não foi possível preparar sua conta. Tente novamente.",
    retry: "Tentar novamente",
  },
  roles: { owner: "Proprietário", admin: "Administrador", editor: "Editor" },
  pages: {
    listTitle: "Páginas",
    usage: (used: number, limit: number) => `${used} de ${limit} ${limit === 1 ? "página" : "páginas"}`,
    create: "Nova página",
    emptyTitle: "Você ainda não criou nenhuma página.",
    emptyDescription: "Crie sua primeira página para escolher o endereço e começar a montar o conteúdo.",
    limitReached: (limit: number) => `Esta conta já usa ${limit === 1 ? "sua página disponível" : `as ${limit} páginas disponíveis`} no plano atual. Para criar outra, exclua uma página existente.`,
    createForbidden: "Somente proprietários e administradores criam páginas nesta conta.",
    status: { draft: "Rascunho", published: "Publicada", archived: "Arquivada" },
    settings: "Editar",
    publishHint: "Visitantes só veem uma página depois que ela é publicada. Abra o editor da página para montar os blocos e publicar.",
    notFoundTitle: "Página não encontrada",
    notFound: "Esta página não existe, foi excluída ou você não tem acesso a ela.",
  },
  onboarding: {
    eyebrow: "Primeiros passos",
    title: "Crie sua primeira página",
    lead: "Comece pelo básico. Você poderá editar tudo depois.",
    submit: "Criar página",
    skip: "Fazer isso depois",
  },
  profileForm: {
    title: "Nome da página",
    titleHint: "Aparece no topo da página. Ex.: Café Ipê ou Ana Lima — Nutrição.",
    titleError: "Informe um nome de 1 a 80 caracteres.",
    slug: "Endereço da página",
    slugHint: "Letras, números e hífens. Acentos e espaços são ajustados automaticamente.",
    checking: "Verificando disponibilidade…",
    bio: "Apresentação (opcional)",
    bioHint: (remaining: number) => `Até 280 caracteres. Restam ${remaining}.`,
    bioError: "Use no máximo 280 caracteres.",
    avatar: "Foto ou logo",
    avatarPlaceholder: "O envio de imagem chega em breve. Por enquanto, mostramos suas iniciais.",
    created: "Página criada como rascunho.",
    saved: "Alterações salvas.",
    save: "Salvar alterações",
  },
  slugChange: {
    open: "Alterar endereço",
    title: "Alterar endereço da página",
    warning: "O endereço atual muda na hora. Por 90 dias, quem abrir o link antigo será levado ao novo enquanto a página estiver publicada, e ninguém de fora desta conta pode usá-lo. Depois disso o link antigo deixa de funcionar: atualize-o onde você divulgou.",
    confirm: "Alterar endereço",
    cancel: "Cancelar",
    changed: (slug: string) => `Endereço alterado para ${slug}.`,
    forbidden: "Somente proprietários e administradores alteram o endereço.",
  },
  deletePage: {
    open: "Excluir página",
    title: "Excluir esta página?",
    warning: "A página sai da sua lista e o endereço deixa de funcionar. Os dados ficam guardados por 30 dias para recuperação pelo suporte e depois são apagados.",
    confirm: "Excluir página",
    cancel: "Cancelar",
    deleted: "Página excluída.",
    forbidden: "Somente proprietários e administradores excluem páginas.",
  },
  draft: {
    conflict: "Esta página foi alterada em outra aba ou por outra pessoa. Recarregue para ver a versão atual e tente de novo.",
    invalid: "Algum conteúdo não é aceito. Revise os blocos e tente novamente.",
    notice: "Tudo o que você edita aqui fica no rascunho até você publicar.",
  },
  errors: {
    forbidden: "Você não tem permissão para fazer isso nesta conta.",
    notFound: "Não encontramos este item ou você não tem acesso a ele.",
    unavailable: "Não foi possível concluir agora. Tente novamente em instantes.",
    sessionExpired: "Sua sessão expirou. Entre novamente para continuar.",
  },
  nav: { home: "Início", skipToContent: "Pular para o conteúdo" },
} as const;

export const PUBLISHING_COPY = {
  title: "Publicação",
  state: {
    never: "Esta página ainda não foi publicada. Visitantes veem a mensagem de página não encontrada.",
    live_current: "Publicada. O que está no ar é igual ao rascunho.",
    live_outdated: "Publicada, com alterações no rascunho que ainda não estão no ar.",
    offline: "Fora do ar. Publique de novo ou restaure uma versão anterior.",
  },
  badge: { never: "Rascunho", live_current: "No ar", live_outdated: "Alterações não publicadas", offline: "Fora do ar" },
  liveSince: (date: string) => `No ar desde ${date}.`,
  publish: "Publicar",
  publishChanges: "Publicar alterações",
  upToDate: "Tudo publicado",
  published: (version: number) => `Página publicada (versão ${version}). Ela já está no ar.`,
  alreadyPublished: "Nada novo para publicar: esta versão já está no ar.",
  preview: "Ver prévia do rascunho",
  openPublic: "Abrir página publicada",
  openPublicHint: "Abre em uma nova aba.",
  versionsTitle: "Versões publicadas",
  versionsLead: "Guardamos as 10 publicações mais recentes. Restaurar coloca a versão escolhida no ar sem mudar o seu rascunho.",
  versionLabel: (version: number) => `Versão ${version}`,
  versionLive: "No ar",
  restore: "Restaurar",
  restoreLabel: (version: number) => `Restaurar a versão ${version}`,
  restored: (version: number) => `Versão ${version} restaurada e no ar.`,
  unpublish: {
    open: "Tirar do ar",
    title: "Tirar esta página do ar?",
    warning: "Visitantes passam a ver “página não encontrada”. O rascunho e as versões continuam guardados e você pode publicar ou restaurar quando quiser.",
    confirm: "Tirar do ar",
    cancel: "Cancelar",
    done: "Página fora do ar.",
  },
  forbidden: "Você pode ver o estado da publicação, mas não publicar nesta conta.",
  errors: {
    stale: "O rascunho mudou desde que você abriu esta tela. Confira a prévia e publique de novo.",
    forbidden: "Você não tem permissão para publicar nesta conta, ou a conta está suspensa.",
    unavailable: "Não foi possível publicar agora. Nada mudou na página no ar. Tente novamente em instantes.",
  },
  previewBanner: "Prévia do rascunho. Visitantes ainda não veem estas alterações.",
  previewBack: "Voltar ao editor",
} as const;

export const PUBLIC_PAGE_COPY = {
  notFoundTitle: "Página não encontrada",
  notFound: "Não existe uma página publicada neste endereço. Confira se o link está correto.",
  suspendedTitle: "Página indisponível",
  suspended: "Esta página está temporariamente indisponível.",
  errorTitle: "Não foi possível carregar esta página",
  error: "Tente novamente em instantes.",
  retry: "Tentar novamente",
  badge: (product: string) => `Criado com ${product}`,
  defaultDescription: (title: string) => `Links e contatos de ${title}.`,
  socialLabel: "Redes sociais",
  linksLabel: "Links",
  opensExternal: (network: string) => `${network} (abre fora desta página)`,
  goHome: "Ir para a página inicial",
  whatsappSuffix: " (WhatsApp)",
} as const;

/** Block types, fields and validation messages (Sprint 4 editor). */
export const BLOCKS_COPY = {
  types: {
    link: { label: "Link", description: "Botão que leva a um site, e-mail ou telefone." },
    text: { label: "Texto", description: "Parágrafo curto para explicar algo ou dar um aviso." },
    social: { label: "Redes sociais", description: "Ícones para seus perfis no Instagram, TikTok e outras redes." },
    whatsapp: { label: "WhatsApp", description: "Botão que abre uma conversa no WhatsApp, com mensagem pronta." },
    divider: { label: "Separador", description: "Linha para dividir a página em partes." },
  },
  fields: {
    linkTitle: "Texto do botão",
    linkTitleHint: "Ex.: Agende uma consulta, Cardápio, Portfólio.",
    linkUrl: "Endereço de destino",
    linkUrlHint: "Site (exemplo.com.br), e-mail (mailto:voce@exemplo.com) ou telefone (tel:+5511…).",
    text: "Texto",
    textHint: (remaining: number) => `Até 1.000 caracteres. Restam ${remaining}. Quebras de linha são mantidas.`,
    whatsappLabel: "Texto do botão",
    whatsappLabelHint: "Ex.: Fale comigo no WhatsApp.",
    whatsappPhone: "Número do WhatsApp",
    whatsappPhoneHint: "Com DDD, ex.: (11) 91234-5678. Para outro país, comece com + e o código do país.",
    whatsappMessage: "Mensagem pronta (opcional)",
    whatsappMessageHint: (remaining: number) => `Aparece escrita quando a conversa abre. Restam ${remaining} caracteres.`,
    socialLead: "Cole o link do perfil ou só o @. Deixe em branco as redes que você não usa.",
    socialPlaceholder: "@seuperfil ou link do perfil",
    dividerLead: "O separador não tem campos. Use os botões de mover para posicioná-lo.",
  },
  errors: {
    titleLength: "Informe um texto de 1 a 80 caracteres.",
    textLength: "Escreva de 1 a 1.000 caracteres.",
    messageLength: "Use no máximo 500 caracteres.",
    controlCharacters: "O texto tem caracteres especiais que não são aceitos. Apague e digite de novo.",
    url: {
      required: "Informe o endereço de destino.",
      scheme: "Esse tipo de link não é permitido. Use um site (https://), e-mail (mailto:) ou telefone (tel:).",
      relative: "Informe o endereço completo, por exemplo exemplo.com.br.",
      whitespace: "O endereço não pode ter espaços.",
      credentials: "Links com usuário ou senha no endereço não são permitidos.",
      host: "Confira o endereço: falta o domínio (como .com ou .com.br).",
      email: "Confira o e-mail: use o formato mailto:voce@exemplo.com.",
      phone: "Confira o telefone: use o formato tel:+5511912345678.",
      tooLong: "Endereço muito longo (máximo de 2.048 caracteres).",
    },
    whatsappPhone: "Informe um número válido com DDD, ex.: (11) 91234-5678. Para outro país, comece com +.",
    social: "Endereço inválido. Cole o link do perfil ou só o @.",
    socialWrongNetwork: (network: string) => `Este link não é do ${network}. Use um endereço do próprio ${network}.`,
  },
  insecureLink: "Este site não usa conexão segura (https). Se ele tiver versão https, prefira-a.",
  punycodeNotice: "Endereços com acentos aparecem no formato técnico (xn--) para que imitações de sites fiquem visíveis.",
  summary: {
    emptyText: "Texto vazio",
    emptyLink: "Link sem destino",
    emptySocial: "Nenhuma rede preenchida",
    socialCount: (count: number) => `${count} ${count === 1 ? "rede" : "redes"}`,
    divider: "Linha divisória",
  },
} as const;

/** Block editor chrome, autosave and conflict texts (Sprint 4). */
export const EDITOR_COPY = {
  headerSection: "Cabeçalho",
  blocksSection: "Blocos",
  blocksLead: "Monte a página na ordem em que os visitantes vão ver.",
  emptyTitle: "Sua página ainda não tem blocos.",
  emptyDescription: "Adicione o primeiro bloco: um link, um botão de WhatsApp ou suas redes sociais.",
  addBlock: "Adicionar bloco",
  addBlockTitle: "Qual bloco você quer adicionar?",
  addBlockLead: "O novo bloco entra logo depois do bloco aberto, ou no fim da página.",
  blockLimit: "Esta página chegou ao limite de 100 blocos.",
  payloadLimit: "A página ficou grande demais para salvar. Remova ou encurte alguns blocos.",
  hiddenBadge: "Oculto: não aparece na página",
  invalidBadge: "Precisa de ajuste",
  actions: {
    editPrefix: "Editar",
    moveUp: (name: string) => `Mover ${name} para cima`,
    moveDown: (name: string) => `Mover ${name} para baixo`,
    moveTop: "Mover para o topo",
    moveBottom: "Mover para o fim",
    duplicate: "Duplicar",
    duplicateLabel: (name: string) => `Duplicar ${name}`,
    hide: "Ocultar",
    show: "Mostrar",
    hideLabel: (name: string) => `Ocultar ${name} da página`,
    showLabel: (name: string) => `Mostrar ${name} na página`,
    delete: "Excluir",
    deleteLabel: (name: string) => `Excluir ${name}`,
    done: "Concluir",
  },
  blockName: (typeLabel: string, position: number) => `bloco ${position}, ${typeLabel}`,
  announce: {
    added: (typeLabel: string, position: number, total: number) => `Bloco ${typeLabel} adicionado na posição ${position} de ${total}.`,
    moved: (position: number, total: number) => `Bloco movido para a posição ${position} de ${total}.`,
    duplicated: (position: number, total: number) => `Bloco duplicado na posição ${position} de ${total}.`,
    hidden: "Bloco oculto. Ele não aparece na página publicada.",
    shown: "Bloco visível na página.",
    deleted: "Bloco excluído. Use Desfazer para trazê-lo de volta.",
    restored: (position: number) => `Bloco restaurado na posição ${position}.`,
    loadedLatest: "Versão mais recente carregada.",
  },
  undo: { deleted: "Bloco excluído.", action: "Desfazer", dismiss: "Fechar aviso" },
  status: {
    saved: "Salvo",
    saving: "Salvando…",
    retrying: "Sem resposta do servidor. Tentando salvar de novo…",
    dirty: "Alterações não salvas",
    invalid: "Não salvo: corrija os campos destacados.",
    error: "Não foi possível salvar.",
    conflict: "Não salvo: a página mudou em outro lugar.",
    retry: "Tentar novamente",
  },
  saveErrors: {
    validation: "Algum conteúdo não foi aceito pelo servidor. Revise os blocos e tente novamente.",
    forbidden: "Você não tem mais permissão para editar esta página, ou a conta está suspensa.",
    notFound: "Esta página não existe mais ou você perdeu o acesso a ela.",
    sessionExpired: "Sua sessão expirou. Entre novamente em outra aba e depois clique em Tentar novamente.",
    unavailable: "O servidor não respondeu. Suas alterações continuam aqui.",
  },
  conflict: {
    title: "Esta página foi alterada em outro lugar",
    lead: "Outra aba ou outra pessoa salvou mudanças enquanto você editava. Suas alterações continuam aqui até você escolher o que fazer.",
    loadLatest: "Carregar a versão mais recente",
    keepMine: "Manter as minhas alterações",
    loadLatestConfirmTitle: "Descartar as suas alterações?",
    loadLatestConfirm: "O editor vai mostrar a versão salva mais recente. As alterações feitas nesta aba desde o último salvamento serão perdidas.",
    loadLatestAction: "Descartar e carregar",
    keepMineConfirmTitle: "Substituir a versão salva?",
    keepMineConfirm: "A versão desta aba vai substituir a que foi salva em outro lugar. As mudanças feitas lá serão perdidas.",
    keepMineAction: "Substituir pela minha versão",
    cancel: "Cancelar",
    failed: "Não foi possível carregar a versão mais recente. Tente novamente.",
  },
  leaveWarning: "Há alterações que ainda não foram salvas. Sair mesmo assim?",
  view: { label: "Modo de visualização", edit: "Editar", preview: "Pré-visualizar" },
  preview: {
    title: "Pré-visualização",
    banner: "Prévia do rascunho. Os links não funcionam aqui.",
    untitled: "Sua página",
  },
  publish: {
    blockedSaving: "Aguarde salvar para publicar.",
    blockedInvalid: "Corrija os blocos destacados para publicar.",
    blockedConflict: "Resolva o conflito para publicar.",
    blockedError: "Salve as alterações para publicar.",
  },
  readOnly: "Você pode ver esta página, mas não editá-la nesta conta.",
} as const;
