import Link from "next/link";
import { PRODUCT } from "@/lib/product";
import { WaitlistForm } from "@/modules/waitlist/waitlist-form";
import type { WaitlistVariant } from "@/modules/waitlist/types";

const COPY = {
  neutral: { eyebrow: "Hub de conversão mobile em construção", title: "Transforme visitas da bio em próximos passos claros.", description: "Crie uma página profissional, leve pessoas ao WhatsApp, agenda, formulário ou pagamento externo e entenda quais caminhos geram resultado.", bullets: ["Página profissional em poucos minutos", "WhatsApp, Pix, agenda e formulários", "Resultados claros e operação multi-perfil"] },
  agencies: { eyebrow: "Piloto para quem administra clientes", title: "Todas as páginas dos seus clientes em uma só conta.", description: "Duplique estruturas, publique mais rápido e compartilhe um relatório que o cliente entende — sem limitar o produto somente a agências.", bullets: ["Visão consolidada de várias páginas", "Templates e duplicação sem conteúdo compartilhado", "Relatório somente leitura para o cliente"] },
  professionals: { eyebrow: "Piloto para profissionais e pequenos negócios", title: "Uma página simples para transformar atenção em conversa.", description: "Reúna seus caminhos mais importantes e acompanhe quais visitas avançam para WhatsApp, agenda, formulário ou pagamento externo.", bullets: ["Visual profissional e mobile-first", "Chamadas para ação locais e diretas", "Dados em linguagem simples"] },
} as const;

export function Landing({ variant }: { variant: WaitlistVariant }) {
  const content = COPY[variant];
  return <main><header className="app-shell flex min-h-20 items-center justify-between gap-4"><Link className="font-bold" href="/">{PRODUCT.codename}</Link><span className="ui-badge ui-badge-warning">Nome provisório</span></header><section className="app-shell grid gap-10 py-14 lg:grid-cols-[1.05fr_0.95fr] lg:items-start lg:py-24"><div className="lg:sticky lg:top-10"><p className="text-sm font-bold uppercase tracking-[0.16em] text-app-accent">{content.eyebrow}</p><h1 className="mt-4 max-w-3xl text-4xl font-bold leading-tight tracking-tight sm:text-6xl">{content.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-app-muted">{content.description}</p><ul className="mt-8 grid gap-3">{content.bullets.map((item) => <li key={item} className="flex gap-3"><span className="text-app-success" aria-hidden="true">✓</span><span>{item}</span></li>)}</ul><div className="mt-8 rounded-2xl bg-app-accent/10 p-5 text-app-accent"><b>O produto está em construção.</b><p className="mt-1">Estamos formando a lista do piloto. Planos em reais estão sendo pesquisados; ainda não há oferta ou preço definitivo.</p></div></div><section className="surface-card p-6 sm:p-8" id="lista"><h2 className="text-3xl font-bold">Entrar na lista</h2><p className="mt-2 text-app-muted">Conte um pouco do seu contexto. Leva cerca de dois minutos.</p><div className="mt-6"><WaitlistForm variant={variant} /></div></section></section><footer className="border-t border-app-border py-8"><div className="app-shell flex flex-wrap justify-between gap-4 text-sm text-app-muted"><span>{PRODUCT.codename} • codinome provisório</span><Link className="underline" href="/privacidade">Privacidade — versão provisória</Link></div></footer></main>;
}
