"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useState } from "react";
import { applyTemplate, buildWhatsAppUrl, editorReducer, hasValueAction, hasVisibleBlock, validateSlug, type Block, type BlockType, type EditorState, type PageDocument } from "@/modules/editor/model";
import { TEMPLATES } from "@/modules/editor/templates";
import { BioPage } from "@/modules/publishing/render/bio-page";
import { Badge, Button, Dialog, DialogActions, EmptyState, IconButton, SaveStatus, SelectField, Switch, TextAreaField, TextField, Toast, type SaveState } from "@/ui";
import { usePrototype } from "../store";

const BLOCK_LABELS: Record<BlockType, string> = { link: "Link", text: "Texto", social: "Redes sociais", whatsapp: "WhatsApp", pix: "Pix / pagamento", form: "Formulário", image: "Imagem", video: "Vídeo", separator: "Separador" };
const BLOCK_GROUPS: Array<{ label: string; types: BlockType[] }> = [{ label: "Converter", types: ["whatsapp", "pix", "form", "link"] }, { label: "Conteúdo", types: ["text", "image", "video", "separator"] }, { label: "Redes", types: ["social"] }];

function createBlock(type: BlockType): Block {
  const id = `${type}-${Date.now()}`;
  switch (type) {
    case "link": return { id, type, visible: true, valueAction: false, title: "Meu link", url: "https://example.com" };
    case "text": return { id, type, visible: true, valueAction: false, text: "Conte um pouco sobre seu trabalho." };
    case "social": return { id, type, visible: true, valueAction: false, items: [{ network: "instagram", url: "https://instagram.com/exemplo" }] };
    case "whatsapp": return { id, type, visible: true, valueAction: true, label: "Falar no WhatsApp", phone: "+55 11 99999-0000", message: "Olá! Vim pela sua página." };
    case "pix": return { id, type, visible: true, valueAction: true, label: "Copiar chave Pix", keyType: "email", key: "pagamento@exemplo.test", paymentUrl: "" };
    case "form": return { id, type, visible: true, valueAction: true, title: "Entre em contato", fields: ["name", "email", "message"], consentText: "Aceito o uso dos meus dados para responder a este contato." };
    case "image": return { id, type, visible: true, valueAction: false, src: "/samples/cafe.svg", alt: "Mesa com uma xícara de café", aspectRatio: "4/3" };
    case "video": return { id, type, visible: true, valueAction: false, title: "Assista ao vídeo", url: "https://youtube.com/watch?v=demo", provider: "youtube" };
    case "separator": return { id, type, visible: true, valueAction: false, style: "line" };
  }
}

function BlockFields({ block, onChange }: { block: Block; onChange: (block: Block) => void }) {
  if (block.type === "link") return <div className="grid gap-3"><TextField id={`${block.id}-title`} label="Texto do botão" value={block.title} onChange={(e) => onChange({ ...block, title: e.target.value })} /><TextField id={`${block.id}-url`} label="Destino" value={block.url} onChange={(e) => onChange({ ...block, url: e.target.value })} hint="Adicionamos https:// quando necessário e bloqueamos endereços perigosos." /><Switch checked={block.valueAction} label="Contar como resultado" onChange={(value) => onChange({ ...block, valueAction: value })} /></div>;
  if (block.type === "text") return <TextAreaField id={`${block.id}-text`} label="Texto" value={block.text} onChange={(e) => onChange({ ...block, text: e.target.value })} />;
  if (block.type === "social") { const first = block.items[0] ?? { network: "instagram" as const, url: "" }; return <div className="grid gap-3"><SelectField id={`${block.id}-network`} label="Rede" value={first.network} onChange={(e) => onChange({ ...block, items: [{ ...first, network: e.target.value as typeof first.network }] })}><option value="instagram">Instagram</option><option value="tiktok">TikTok</option><option value="youtube">YouTube</option><option value="linkedin">LinkedIn</option></SelectField><TextField id={`${block.id}-social-url`} label="Endereço do perfil" value={first.url} onChange={(e) => onChange({ ...block, items: [{ ...first, url: e.target.value }] })} /></div>; }
  if (block.type === "whatsapp") { const result = buildWhatsAppUrl(block.phone, block.message); return <div className="grid gap-3"><TextField id={`${block.id}-label`} label="Texto do botão" value={block.label} onChange={(e) => onChange({ ...block, label: e.target.value })} /><TextField id={`${block.id}-phone`} label="WhatsApp com DDD" value={block.phone} onChange={(e) => onChange({ ...block, phone: e.target.value })} error={result.ok ? undefined : result.reason} hint="Números brasileiros recebem o código +55." /><TextAreaField id={`${block.id}-message`} label="Mensagem pronta (opcional)" value={block.message} onChange={(e) => onChange({ ...block, message: e.target.value })} />{result.ok ? <p className="ui-hint break-all">Destino gerado: {result.url}</p> : null}<Badge tone="success">Conta como resultado</Badge></div>; }
  if (block.type === "pix") return <div className="grid gap-3"><TextField id={`${block.id}-pix-label`} label="Título" value={block.label} onChange={(e) => onChange({ ...block, label: e.target.value })} /><SelectField id={`${block.id}-pix-type`} label="Tipo de chave" value={block.keyType} onChange={(e) => onChange({ ...block, keyType: e.target.value as typeof block.keyType })}><option value="cpf">CPF</option><option value="cnpj">CNPJ</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="random">Aleatória</option></SelectField><TextField id={`${block.id}-pix-key`} label="Chave Pix" value={block.key} onChange={(e) => onChange({ ...block, key: e.target.value })} /><TextField id={`${block.id}-payment`} label="Link de pagamento externo (opcional)" value={block.paymentUrl ?? ""} onChange={(e) => onChange({ ...block, paymentUrl: e.target.value })} hint="A plataforma apenas mostra a chave ou abre um parceiro; não processa o pagamento." /><Badge tone="success">Conta como resultado</Badge></div>;
  if (block.type === "separator") return <SelectField id={`${block.id}-style`} label="Estilo" value={block.style} onChange={(e) => onChange({ ...block, style: e.target.value as typeof block.style })}><option value="line">Linha</option><option value="dots">Pontos</option><option value="space">Espaço</option></SelectField>;
  if (block.type === "image") return <div className="grid gap-3"><SelectField id={`${block.id}-image`} label="Imagem de exemplo" value={block.src} onChange={(e) => onChange({ ...block, src: e.target.value })}><option value="/samples/cafe.svg">Café</option><option value="/samples/studio.svg">Estúdio</option><option value="/samples/shop.svg">Loja</option></SelectField><TextField id={`${block.id}-alt`} label="Descrição da imagem" value={block.alt} onChange={(e) => onChange({ ...block, alt: e.target.value })} /></div>;
  if (block.type === "video") return <div className="grid gap-3"><TextField id={`${block.id}-video-title`} label="Título" value={block.title} onChange={(e) => onChange({ ...block, title: e.target.value })} /><TextField id={`${block.id}-video-url`} label="URL do YouTube ou Vimeo" value={block.url} onChange={(e) => onChange({ ...block, url: e.target.value, provider: e.target.value.includes("vimeo") ? "vimeo" : e.target.value.includes("youtu") ? "youtube" : "unknown" })} /></div>;
  return <div className="grid gap-3"><TextField id={`${block.id}-form-title`} label="Título do formulário" value={block.title} onChange={(e) => onChange({ ...block, title: e.target.value })} /><p className="ui-hint">Campos fixos nesta sprint: nome, e-mail e mensagem.</p><TextAreaField id={`${block.id}-consent`} label="Texto de consentimento" value={block.consentText} onChange={(e) => onChange({ ...block, consentText: e.target.value })} /><Badge tone="success">Conta como resultado</Badge></div>;
}

function ThemePanel({ document, onChange }: { document: PageDocument; onChange: (document: PageDocument) => void }) {
  return <div className="grid gap-4"><div><h2 className="text-xl font-bold">Tema</h2><p className="mt-1 text-sm text-app-muted">Trocar o modelo visual nunca apaga seus blocos ou textos.</p></div><SelectField id="theme-template" label="Modelo visual" value={document.theme.id} onChange={(e) => { const template = TEMPLATES.find((item) => item.theme.id === e.target.value); if (template) onChange(applyTemplate(document, template)); }}>{TEMPLATES.map((template) => <option key={template.id} value={template.theme.id}>{template.name}</option>)}</SelectField><TextField id="theme-accent" label="Cor de destaque" type="color" value={document.theme.buttonBg} onChange={(e) => onChange({ ...document, theme: { ...document.theme, buttonBg: e.target.value } })} /><SelectField id="theme-font" label="Combinação de fontes" value={document.theme.pageFont} onChange={(e) => onChange({ ...document, theme: { ...document.theme, pageFont: e.target.value } })}><option value="Arial, Helvetica, sans-serif">Arial + sistema</option><option value="Trebuchet MS, Arial, sans-serif">Trebuchet + sistema</option><option value="Verdana, Arial, sans-serif">Verdana + sistema</option></SelectField><SelectField id="theme-button" label="Estilo dos botões" value={document.theme.buttonStyle} onChange={(e) => onChange({ ...document, theme: { ...document.theme, buttonStyle: e.target.value as typeof document.theme.buttonStyle } })}><option value="filled">Preenchido</option><option value="outline">Contorno</option><option value="soft">Suave</option></SelectField><label className="ui-field"><span className="ui-label">Arredondamento: {document.theme.buttonRadius}px</span><input type="range" min="0" max="32" step="4" value={document.theme.buttonRadius} onChange={(e) => onChange({ ...document, theme: { ...document.theme, buttonRadius: Number(e.target.value) } })} /></label><TextField id="theme-bg" label="Cor do fundo" type="color" value={document.theme.pageBg} onChange={(e) => onChange({ ...document, theme: { ...document.theme, pageBg: e.target.value } })} /></div>;
}

export function EditorScreen() {
  const params = useParams<{ profileId: string }>(); const { state, updateProfile, record } = usePrototype();
  const stored = state.profiles.find((profile) => profile.id === params.profileId);
  const [document, setDocument] = useState<PageDocument | null>(() => stored ? structuredClone(stored) : null);
  const [saveState, setSaveState] = useState<SaveState>("saved"); const [mobileMode, setMobileMode] = useState<"edit" | "preview">("edit"); const [pickerOpen, setPickerOpen] = useState(false); const [publishOpen, setPublishOpen] = useState(false); const [publishing, setPublishing] = useState(false); const [publishError, setPublishError] = useState(""); const [published, setPublished] = useState(false); const [showUndo, setShowUndo] = useState(false); const [undoState, setUndoState] = useState<EditorState | null>(null);
  if (!document) return <main className="app-shell py-20"><EmptyState title="Página não encontrada" description="Escolha um cenário ou crie uma página antes de abrir o editor." action={<Link className="ui-button ui-button-primary" href="/proto">Voltar ao início</Link>} /></main>;

  const commit = async (next: PageDocument, eventName: "block_added" | "block_edited" = "block_edited") => { setDocument(next); setSaveState("saving"); record(eventName, next.id); await new Promise((resolve) => setTimeout(resolve, state.debug.slowSave ? 1800 : 350)); if (state.debug.forceSaveError) { setSaveState("error"); record("error_shown", "save_failed"); return; } updateProfile(next); setSaveState("saved"); };
  const reduce = (action: Parameters<typeof editorReducer>[1], eventName: "block_added" | "block_edited" = "block_edited") => { const current: EditorState = { document, revision: (undoState?.revision ?? 0) + document.blocks.length, undoDelete: undoState?.undoDelete }; const nextState = editorReducer(current, action); if (action.type === "delete") { setUndoState(nextState); setShowUndo(true); } void commit(nextState.document, eventName); };
  const undoDelete = () => { if (!undoState) return; const restored = editorReducer({ ...undoState, document }, { type: "undo-delete" }); setShowUndo(false); setUndoState(null); void commit(restored.document); };
  const addBlock = (type: BlockType) => { reduce({ type: "add", block: createBlock(type) }, "block_added"); setPickerOpen(false); };
  const preview = () => { setMobileMode("preview"); record("preview_opened", document.id); };
  const slugCheck = validateSlug(document.slug); const visible = hasVisibleBlock(document); const valueAction = hasValueAction(document);
  const publish = async () => { record("publish_clicked", document.id); setPublishing(true); setPublishError(""); await new Promise((resolve) => setTimeout(resolve, 850)); if (state.debug.forcePublishError) { setPublishing(false); setPublishError("Não foi possível publicar. Revise sua conexão e tente novamente."); record("publish_failed", document.id); record("error_shown", "publish_failed"); return; } const next = { ...document, status: "published" as const, publishedAt: new Date().toISOString() }; setDocument(next); updateProfile(next); setPublishing(false); setPublished(true); record("publish_succeeded", document.id); };
  const status = document.status === "draft" ? <Badge>Rascunho</Badge> : document.status === "published" ? <Badge tone="success">Publicado</Badge> : <Badge tone="warning">Publicado com alterações pendentes</Badge>;

  const blockEditor = <div className="grid gap-4"><Button className="w-full" variant="secondary" onClick={() => setPickerOpen(true)}>+ Adicionar bloco</Button>{document.blocks.length === 0 ? <EmptyState title="Sua página está vazia" description="Adicione um bloco para mostrar conteúdo aos visitantes." action={<Button onClick={() => setPickerOpen(true)}>Adicionar primeiro bloco</Button>} /> : document.blocks.map((block, index) => <article key={block.id} className={`surface-card p-4 ${block.visible ? "" : "opacity-65"}`}><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><b>{BLOCK_LABELS[block.type]}</b>{block.valueAction ? <Badge tone="success">Resultado</Badge> : null}{!block.visible ? <Badge>Oculto</Badge> : null}</div><div className="flex flex-wrap gap-1"><IconButton label={`Mover ${BLOCK_LABELS[block.type]} para cima`} disabled={index === 0} onClick={() => reduce({ type: "move", blockId: block.id, direction: "up" })}>↑</IconButton><IconButton label={`Mover ${BLOCK_LABELS[block.type]} para baixo`} disabled={index === document.blocks.length - 1} onClick={() => reduce({ type: "move", blockId: block.id, direction: "down" })}>↓</IconButton><IconButton label={`Duplicar ${BLOCK_LABELS[block.type]}`} onClick={() => reduce({ type: "duplicate", blockId: block.id })}>⧉</IconButton><IconButton label={block.visible ? `Ocultar ${BLOCK_LABELS[block.type]}` : `Mostrar ${BLOCK_LABELS[block.type]}`} onClick={() => reduce({ type: "toggle", blockId: block.id })}>{block.visible ? "◉" : "○"}</IconButton><IconButton label={`Excluir ${BLOCK_LABELS[block.type]}`} onClick={() => reduce({ type: "delete", blockId: block.id })}>×</IconButton></div></div><BlockFields block={block} onChange={(changed) => reduce({ type: "update", block: changed })} /></article>)}</div>;

  return <main className="min-h-screen pb-24 lg:pb-0"><header className="border-b border-app-border bg-app-surface"><div className="app-shell flex min-h-20 flex-wrap items-center justify-between gap-3 py-3"><div><Link className="text-sm font-bold text-app-accent" href={state.scenario === "agency" ? "/proto/w/agencia-aurora/perfis" : "/proto"}>← Voltar</Link><div className="mt-1 flex flex-wrap items-center gap-2"><h1 className="text-xl font-bold">{document.title}</h1>{status}{document.status === "published" && saveState !== "saved" ? <Badge tone="warning">Alterações não publicadas</Badge> : null}</div></div><div className="flex items-center gap-2"><Button variant="secondary" onClick={preview}>Prévia</Button><Button onClick={() => setPublishOpen(true)}>Publicar</Button></div></div></header><div className="app-shell py-5"><div className="mb-5 flex rounded-xl bg-app-surface-soft p-1 lg:hidden"><button className={`ui-button flex-1 ${mobileMode === "edit" ? "ui-button-primary" : "ui-button-ghost"}`} onClick={() => setMobileMode("edit")}>Editar</button><button className={`ui-button flex-1 ${mobileMode === "preview" ? "ui-button-primary" : "ui-button-ghost"}`} onClick={preview}>Visualizar</button></div><div className="grid gap-6 lg:grid-cols-[minmax(0,1.25fr)_minmax(340px,0.85fr)_280px]"><section className={mobileMode === "preview" ? "hidden lg:block" : "block"}><div className="mb-4"><h2 className="text-2xl font-bold">Blocos</h2><p className="text-app-muted">Organize o caminho até o próximo resultado.</p></div>{blockEditor}<div className="surface-card mt-6 p-5 lg:hidden"><ThemePanel document={document} onChange={(next) => void commit(next)} /></div></section><aside className={`${mobileMode === "edit" ? "hidden lg:block" : "block"}`}><div className="sticky top-5 overflow-hidden rounded-[2.2rem] border-[10px] border-app-text bg-app-surface shadow-raised"><div className="h-[72vh] min-h-[580px] overflow-auto"><BioPage document={document} preview /></div></div></aside><aside className="hidden lg:block"><div className="sticky top-5 surface-card p-5"><ThemePanel document={document} onChange={(next) => void commit(next)} /></div></aside></div></div><div className="fixed inset-x-0 bottom-0 z-40 border-t border-app-border bg-app-surface p-3 shadow-raised lg:static lg:mt-5 lg:border-0 lg:bg-transparent lg:shadow-none"><div className="app-shell flex items-center justify-between gap-3"><SaveStatus state={saveState} onRetry={() => void commit(document)} /><Button onClick={() => setPublishOpen(true)}>Publicar</Button></div></div>
    <Dialog open={pickerOpen} onClose={() => setPickerOpen(false)} title="Adicionar bloco"><div className="grid gap-5">{BLOCK_GROUPS.map((group) => <section key={group.label}><h3 className="mb-2 font-bold">{group.label}</h3><div className="grid grid-cols-2 gap-2">{group.types.map((type) => <Button key={type} variant="secondary" onClick={() => addBlock(type)}>{BLOCK_LABELS[type]}</Button>)}</div></section>)}</div></Dialog>
    <Dialog open={publishOpen} onClose={() => { if (!publishing) setPublishOpen(false); }} title={published ? "Página publicada" : "Pronto para publicar?"}>{published ? <div className="grid gap-4"><p className="rounded-xl bg-app-success/10 p-4 font-bold text-app-success">Sua página está disponível no protótipo.</p><TextField id="published-url" label="Endereço público" readOnly value={`http://localhost:3000/proto/p/${document.slug}`} /><div className="flex flex-wrap gap-2"><Button onClick={async () => { await navigator.clipboard.writeText(`${window.location.origin}/proto/p/${document.slug}`); record("public_link_copied", document.id); }}>Copiar link</Button><Link className="ui-button ui-button-secondary" href={`/proto/p/${document.slug}`}>Abrir página</Link><Link className="ui-button ui-button-ghost" href={`/proto/analytics/${document.id}`}>Ver resultados</Link></div><p className="ui-hint">Sugestões: envie no WhatsApp, adicione à bio das redes ou abra em outro dispositivo.</p></div> : <div><ul className="grid gap-3"><li className={`rounded-xl p-3 ${slugCheck.valid ? "bg-app-success/10 text-app-success" : "bg-app-danger/10 text-app-danger"}`}>{slugCheck.valid ? "✓ Endereço válido" : `× ${slugCheck.message}`}</li><li className={`rounded-xl p-3 ${visible ? "bg-app-success/10 text-app-success" : "bg-app-danger/10 text-app-danger"}`}>{visible ? "✓ Pelo menos um bloco visível" : "× Mostre pelo menos um bloco antes de publicar."}</li><li className={`rounded-xl p-3 ${valueAction ? "bg-app-success/10 text-app-success" : "bg-app-warning/10 text-app-warning"}`}>{valueAction ? "✓ Há um resultado configurado" : "! Nenhum resultado configurado. Você pode publicar, mas os relatórios terão menos contexto."}</li></ul>{publishError ? <p className="mt-4 rounded-xl bg-app-danger/10 p-3 font-bold text-app-danger" role="alert">{publishError}</p> : null}<DialogActions><Button variant="secondary" disabled={publishing} onClick={() => setPublishOpen(false)}>Continuar editando</Button><Button loading={publishing} disabled={!slugCheck.valid || !visible} onClick={() => void publish()}>Confirmar publicação</Button></DialogActions></div>}</Dialog>
    {showUndo ? <Toast actionLabel="Desfazer" onAction={undoDelete}>Bloco excluído.</Toast> : null}
  </main>;
}
