"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState, type FormEvent } from "react";
import { applyTemplate, validateSlug, type PageDocument } from "@/modules/editor/model";
import { TEMPLATES } from "@/modules/editor/templates";
import { Button, TextField } from "@/ui";
import { usePrototype } from "../store";

export function PrototypeIndexScreen() {
  const router = useRouter();
  const { chooseScenario, reset, state } = usePrototype();
  const start = (scenario: "new-user" | "agency") => { chooseScenario(scenario); router.push(scenario === "new-user" ? "/proto/cadastro" : "/proto/w/agencia-aurora/perfis"); };
  return <main className="app-shell py-16 sm:py-24"><header className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-app-accent">Teste de experiência • dados locais</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-6xl">Escolha uma jornada para testar</h1><p className="mt-5 text-lg leading-8 text-app-muted">Nada aqui cria uma conta ou publica uma página real. O protótipo guarda o progresso somente neste navegador.</p></header><div className="mt-10 grid gap-5 md:grid-cols-2"><section className="surface-card grid gap-4 p-6"><span className="ui-badge ui-badge-accent w-fit">Jornada individual</span><h2 className="text-2xl font-bold">Novo usuário</h2><p className="text-app-muted">Passe por cadastro, escolha de objetivo, edição, preview, publicação e resultados.</p><Button onClick={() => start("new-user")}>Começar do zero</Button></section><section className="surface-card grid gap-4 p-6"><span className="ui-badge ui-badge-warning w-fit">Jornada de agência</span><h2 className="text-2xl font-bold">Agência com 3 clientes</h2><p className="text-app-muted">Busque páginas, duplique um modelo e crie um relatório para o cliente.</p><Button onClick={() => start("agency")}>Abrir conta da agência</Button></section></div><div className="mt-8 flex flex-wrap gap-3"><Button variant="secondary" onClick={reset}>Reiniciar protótipo</Button><Link className="ui-button ui-button-ghost" href="/proto/tokens">Ver tokens de interface</Link></div><p className="mt-4 text-sm text-app-muted">Cenário atual: {state.scenario === "agency" ? "Agência com 3 clientes" : "Novo usuário"}.</p></main>;
}

export function SignupScreen() {
  const router = useRouter();
  const { record, setUser } = usePrototype();
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const [submitted, setSubmitted] = useState(false); const [loading, setLoading] = useState(false); const [generalError, setGeneralError] = useState("");
  const errors = { name: name.trim().length < 2 ? "Informe como você quer ser chamado." : "", email: /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) ? "" : "Digite um e-mail válido.", password: password.length >= 8 ? "" : "Use pelo menos 8 caracteres." };
  const submit = async (event: FormEvent) => { event.preventDefault(); setSubmitted(true); setGeneralError(""); if (errors.name || errors.email || errors.password) { record("error_shown", "signup_validation"); return; } setLoading(true); await new Promise((resolve) => setTimeout(resolve, 650)); if (email.toLowerCase().includes("erro")) { setLoading(false); setGeneralError("Não foi possível concluir o cadastro simulado. Tente outro e-mail para continuar."); record("error_shown", "signup_simulated"); return; } setUser({ name: name.trim(), email: email.trim() }); record("signup_completed"); router.push("/proto/onboarding"); };
  return <main className="app-shell grid min-h-screen items-center py-16 lg:grid-cols-[0.9fr_1.1fr] lg:gap-16"><section className="hidden lg:block"><p className="text-sm font-bold uppercase tracking-[0.16em] text-app-accent">Primeiro passo</p><h1 className="mt-3 text-5xl font-bold tracking-tight">Sua página no ar em menos de 10 minutos.</h1><p className="mt-5 text-lg leading-8 text-app-muted">Este cadastro é simulado. Nenhuma senha sai do navegador ou é enviada a um servidor.</p></section><form className="surface-card grid gap-5 p-6 sm:p-9" onSubmit={submit} noValidate><Link className="w-fit font-bold text-app-accent" href="/proto">← Voltar</Link><div><h1 className="text-3xl font-bold lg:hidden">Crie seu acesso</h1><h2 className="hidden text-3xl font-bold lg:block">Crie seu acesso</h2><p className="mt-2 text-app-muted">Dados usados apenas durante esta sessão de teste.</p></div><TextField id="signup-name" label="Seu nome" autoComplete="name" value={name} onChange={(e) => setName(e.target.value)} error={submitted ? errors.name : undefined} /><TextField id="signup-email" label="E-mail" type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} error={submitted ? errors.email : undefined} hint="Use um e-mail com “erro” para demonstrar a falha simulada." /><TextField id="signup-password" label="Senha" type="password" autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} error={submitted ? errors.password : undefined} />{generalError ? <p className="rounded-xl bg-app-danger/10 p-3 font-bold text-app-danger" role="alert">{generalError}</p> : null}<Button type="submit" loading={loading}>Continuar</Button><Button type="button" variant="secondary" disabled>Continuar com Google — em breve</Button></form></main>;
}

const GOALS = [{ id: "whatsapp", label: "Vender pelo WhatsApp", templates: ["negocio-local", "loja"] }, { id: "leads", label: "Captar contatos", templates: ["criador", "evento"] }, { id: "content", label: "Divulgar conteúdo", templates: ["criador", "evento"] }, { id: "booking", label: "Receber agendamentos", templates: ["profissional", "negocio-local"] }] as const;

export function OnboardingScreen() {
  const router = useRouter(); const { addProfile, record, state } = usePrototype();
  const [goal, setGoal] = useState<(typeof GOALS)[number]["id"]>("whatsapp"); const [templateId, setTemplateId] = useState("negocio-local"); const [slug, setSlug] = useState("");
  const validation = useMemo(() => validateSlug(slug, state.profiles.map((profile) => profile.slug)), [slug, state.profiles]);
  const suggestions = GOALS.find((item) => item.id === goal)?.templates ?? [];
  const submit = (event: FormEvent) => { event.preventDefault(); if (!validation.valid) { record("error_shown", `slug_${validation.status}`); return; } const template = TEMPLATES.find((item) => item.id === templateId) ?? TEMPLATES[0]; const empty: PageDocument = { id: "novo", workspaceId: "personal", title: state.user?.name ? `Página de ${state.user.name}` : "Minha página", bio: "Tudo o que você precisa em um só lugar.", slug: validation.normalized, status: "draft", plan: "free", blocks: [], theme: structuredClone(TEMPLATES[0].theme) }; addProfile(applyTemplate(empty, template)); record("goal_selected", goal); record("template_selected", template.id); record("slug_chosen", validation.normalized); router.push("/proto/editor/novo"); };
  return <main className="app-shell py-16"><div className="mx-auto max-w-4xl"><Link className="font-bold text-app-accent" href="/proto/cadastro">← Voltar</Link><p className="mt-8 text-sm font-bold uppercase tracking-[0.16em] text-app-accent">Configuração guiada</p><h1 className="mt-2 text-4xl font-bold">O que você quer que sua página gere?</h1><p className="mt-3 text-app-muted">Sua resposta muda as sugestões, mas você poderá editar tudo depois.</p><form className="mt-8 grid gap-8" onSubmit={submit}><fieldset><legend className="ui-label mb-3">1. Escolha um objetivo</legend><div className="grid gap-3 sm:grid-cols-2">{GOALS.map((item) => <label key={item.id} className={`surface-card flex min-h-14 cursor-pointer items-center gap-3 p-4 ${goal === item.id ? "border-app-accent bg-app-accent/5" : ""}`}><input type="radio" name="goal" value={item.id} checked={goal === item.id} onChange={() => { setGoal(item.id); const first = item.templates[0]; if (first) setTemplateId(first); }} /> <b>{item.label}</b></label>)}</div></fieldset><fieldset><legend className="ui-label mb-3">2. Comece com um modelo</legend><div className="grid gap-3 md:grid-cols-2">{TEMPLATES.filter((template) => suggestions.includes(template.id as never) || template.id === templateId).map((template) => <label key={template.id} className={`surface-card cursor-pointer p-5 ${templateId === template.id ? "border-app-accent bg-app-accent/5" : ""}`}><input className="mr-2" type="radio" name="template" value={template.id} checked={templateId === template.id} onChange={() => setTemplateId(template.id)} /><b>{template.name}</b><p className="mt-2 text-sm text-app-muted">{template.description}</p></label>)}</div></fieldset><div className="surface-card grid gap-3 p-5"><label className="ui-label" htmlFor="onboarding-slug">3. Escolha o endereço da página</label><div className="flex items-center rounded-xl border border-app-border bg-app-surface"><span className="pl-3 text-sm text-app-muted">projeto.test/</span><input className="ui-input border-0" id="onboarding-slug" value={slug} onChange={(event) => setSlug(event.target.value)} aria-describedby="slug-status" aria-invalid={slug.length > 0 && !validation.valid} /></div>{validation.normalized && validation.normalized !== slug ? <p className="ui-hint">Seu endereço será normalizado para <b>{validation.normalized}</b>.</p> : null}<p id="slug-status" className={validation.valid ? "font-bold text-app-success" : "ui-error"} role="status">{validation.message}</p></div><Button className="w-full sm:w-fit" type="submit">Abrir o editor</Button></form></div></main>;
}
