// Logical backup of the database (docs/runbooks/BACKUP.md).
//
// The production database runs on the Supabase Free plan, which has no managed backups: this script
// IS the backup. It writes, into backups/<UTC time>-<source>/ (ignored by Git):
//
//   roles.sql             cluster roles
//   schema.sql            every object of the application schemas
//   data.sql              rows of public, auth (accounts) and storage (the list of media files)
//   migrations-schema.sql and migrations-data.sql   the migration history, so `supabase db push`
//                         knows what a restored database already has
//   media/                the files of the public `media` bucket (skipped with --no-media)
//   manifest.json         when, from where, rows per table and a SHA-256 per file
//
// What it does NOT contain: Vault secrets (they are encrypted with a key that stays in the
// project; after a restore they are created again, see the runbook), the hosted Auth settings,
// and anything kept only at a provider (Stripe, Vercel).
//
// A backup holds personal data (accounts, leads). Keep it off shared folders and off Git.
//
//   node scripts/db-backup.mjs              production (the linked project); asks the CLI to connect
//   node scripts/db-backup.mjs --local      the local stack (rehearsals)
//   node scripts/db-backup.mjs --no-media   database only
//
// The database password is never taken from the command line: set SUPABASE_DB_PASSWORD in the
// shell, or let the Supabase CLI ask for it. Needs Docker (the CLI runs pg_dump in a container).

import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { createReadStream, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { createInterface } from "node:readline";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const LOCAL = process.argv.includes("--local");
const MEDIA = !process.argv.includes("--no-media");
const SOURCE = LOCAL ? "local" : "production";
// Internal Storage tables the dump role cannot write back; they hold nothing the product uses.
const EXCLUDED = "storage.buckets_vectors,storage.vector_indexes";

function supabase(args, { capture = false } = {}) {
  // One command line for the shell (npx is a .cmd on Windows). Every argument is a constant of this file or a quoted path.
  const result = spawnSync(`npx supabase ${args.join(" ")}`, { cwd: ROOT, shell: true, encoding: "utf8", stdio: capture ? ["ignore", "pipe", "pipe"] : ["inherit", "ignore", "inherit"] });
  if (result.status !== 0) {
    console.error(capture ? result.stderr : "");
    throw new Error(`supabase ${args.slice(0, 3).join(" ")} failed`);
  }
  return capture ? result.stdout : "";
}

function dump(file, flags) {
  supabase(["db", "dump", LOCAL ? "--local" : "--linked", ...flags, "-f", `"${file}"`]);
  if (!existsSync(file) || statSync(file).size === 0) throw new Error(`${file} was not written`);
}

async function sha256(file) {
  const hash = createHash("sha256");
  for await (const chunk of createReadStream(file)) hash.update(chunk);
  return hash.digest("hex");
}

/** Rows per table, counted in the COPY blocks of a data dump, and the media object names found on the way. */
async function inspectData(file) {
  const rows = {};
  const media = [];
  let table = null;
  let columns = [];
  for await (const line of createInterface({ input: createReadStream(file, "utf8"), crlfDelay: Infinity })) {
    if (table === null) {
      const copy = /^COPY "([a-z_]+)"\."([a-z_0-9]+)" \((.*)\) FROM stdin;$/.exec(line);
      if (copy) {
        table = `${copy[1]}.${copy[2]}`;
        columns = copy[3].split(", ").map((name) => name.replace(/"/g, ""));
        rows[table] = 0;
      }
    } else if (line === "\\.") {
      table = null;
    } else {
      rows[table] += 1;
      if (table === "storage.objects") {
        const values = line.split("\t");
        if (values[columns.indexOf("bucket_id")] === "media") media.push(values[columns.indexOf("name")]);
      }
    }
  }
  return { rows, media };
}

function storageBaseUrl() {
  if (LOCAL) return JSON.parse(supabase(["status", "--output", "json"], { capture: true }).replace(/^[^{]*/, "")).API_URL;
  const ref = readFileSync(join(ROOT, "supabase/.temp/project-ref"), "utf8").trim();
  if (!/^[a-z0-9]{20}$/.test(ref)) throw new Error("No linked project (supabase/.temp/project-ref). Run: npx supabase link");
  return `https://${ref}.supabase.co`;
}

async function downloadMedia(names, directory) {
  const base = `${storageBaseUrl()}/storage/v1/object/public/media/`;
  let bytes = 0;
  const failed = [];
  for (const name of names) {
    // Object names are generated by the application (uuid paths); anything else is not written to disk.
    if (!/^[A-Za-z0-9._/-]+$/.test(name) || name.includes("..")) {
      failed.push(name);
      continue;
    }
    try {
      const response = await fetch(base + name.split("/").map(encodeURIComponent).join("/"), { signal: AbortSignal.timeout(30000) });
      if (!response.ok) throw new Error(String(response.status));
      const body = Buffer.from(await response.arrayBuffer());
      const target = join(directory, name);
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, body);
      bytes += body.length;
    } catch {
      failed.push(name);
    }
  }
  return { files: names.length - failed.length, bytes, failed };
}

const startedAt = new Date();
const stamp = startedAt.toISOString().replace(/[-:]/g, "").replace(/\.\d+Z$/, "Z");
const directory = join(ROOT, "backups", `${stamp}-${SOURCE}`);
mkdirSync(directory, { recursive: true });
console.log(`Backing up the ${SOURCE} database into ${directory}`);

const files = {
  "roles.sql": ["--role-only"],
  "schema.sql": [],
  "data.sql": ["--data-only", "--use-copy", "-x", EXCLUDED],
  "migrations-schema.sql": ["--schema", "supabase_migrations"],
  "migrations-data.sql": ["--data-only", "--use-copy", "--schema", "supabase_migrations"],
};
try {
  for (const [name, flags] of Object.entries(files)) {
    console.log(`  ${name}`);
    dump(join(directory, name), flags);
  }
} catch (error) {
  // A partial folder must never be mistaken for a backup.
  rmSync(directory, { recursive: true, force: true });
  console.error(`
No backup was written: ${error.message}.`);
  if (!LOCAL) console.error("For production the Supabase CLI must be signed in to the account that owns the project (npx supabase login), the project must be linked (npx supabase link) and Docker must be running. A 403 means another account is signed in.");
  process.exit(1);
}

const { rows, media } = await inspectData(join(directory, "data.sql"));
const migrations = (await inspectData(join(directory, "migrations-data.sql"))).rows["supabase_migrations.schema_migrations"] ?? 0;

let mediaResult = null;
if (MEDIA) {
  console.log(`  media/ (${media.length} files)`);
  mediaResult = await downloadMedia(media, join(directory, "media"));
}

const manifest = {
  version: 1,
  source: SOURCE,
  startedAt: startedAt.toISOString(),
  finishedAt: new Date().toISOString(),
  migrationsApplied: migrations,
  rows,
  media: mediaResult ? { listed: media.length, downloaded: mediaResult.files, bytes: mediaResult.bytes, failed: mediaResult.failed.length } : null,
  sha256: Object.fromEntries(await Promise.all(Object.keys(files).map(async (name) => [name, await sha256(join(directory, name))]))),
  notIncluded: ["vault secrets", "hosted Auth settings", "provider state (Stripe, Vercel)"],
};
writeFileSync(join(directory, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);

const total = Object.values(rows).reduce((sum, count) => sum + count, 0);
console.log(`\nDone: ${Object.keys(rows).length} tables, ${total} rows, ${migrations} migrations recorded${mediaResult ? `, ${mediaResult.files} of ${media.length} media files` : ""}.`);
console.log(`accounts: ${rows["auth.users"] ?? 0}; pages: ${rows["public.profiles"] ?? 0}; published versions: ${rows["public.profile_publications"] ?? 0}; leads: ${rows["public.form_leads"] ?? 0}`);
if (mediaResult && mediaResult.failed.length > 0) console.log(`WARNING: ${mediaResult.failed.length} media files could not be downloaded (see the runbook).`);
console.log("This folder holds personal data. Copy it somewhere that is not this computer, and check it with:");
console.log(`  node scripts/db-restore-check.mjs "${directory}"`);
if (mediaResult && mediaResult.failed.length > 0) process.exitCode = 1;
