-- Sprint 6: customer analytics. Raw events (short-lived), daily aggregates, the attested anonymous
-- ingestion RPC, the aggregation/purge job and the dashboard read function.
-- Design: docs/adr/0011-customer-analytics.md.
-- Forward-only and additive: the Sprint 5 application keeps working against this schema
-- (submit_form_lead keeps its signature and answers; it additionally records a form_submit event).
-- SQLSTATEs (ADR 0004 contract): 22023 invalid window, 42501 forbidden, P0002 not found.
-- Mirrors: apps/web/src/modules/analytics/*.

-- ---------------------------------------------------------------------------------------------
-- Types (closed sets: nothing a sender controls is stored as free text)
-- ---------------------------------------------------------------------------------------------

-- Mirror of ANALYTICS_EVENT_TYPES in modules/analytics/contract.ts.
create type public.analytics_event_type as enum (
  'page_view', 'link_click', 'social_click', 'embed_load', 'whatsapp_click', 'pix_copy', 'pix_pay_click', 'form_submit', 'badge_click'
);
-- Mirror of TRAFFIC_SOURCES in modules/analytics/sources.ts.
create type public.analytics_source as enum (
  'direct', 'instagram', 'facebook', 'whatsapp', 'tiktok', 'youtube', 'x', 'linkedin', 'telegram', 'google', 'search', 'other'
);
-- Mirror of DEVICE_CLASSES in modules/analytics/device.ts.
create type public.analytics_device as enum ('mobile', 'tablet', 'desktop', 'unknown');
create type public.analytics_dimension as enum ('total', 'block', 'source', 'utm', 'device', 'country');

-- ---------------------------------------------------------------------------------------------
-- Settings: reporting timezone and the day collection started
-- ---------------------------------------------------------------------------------------------

create table public.analytics_settings (
  -- Single row.
  id boolean primary key default true check (id),
  -- Every "day" in analytics is a calendar day in this timezone (provisional: one for all pages).
  reporting_timezone text not null default 'America/Sao_Paulo',
  -- Days before this have no data for any page ("not collected" is not "zero").
  collection_started_at timestamptz not null default now()
);

comment on table public.analytics_settings is
  'Customer-analytics settings (ADR 0011), one row. reporting_timezone defines the day of every event and aggregate; changing it only affects days from then on.';

create function private.validate_analytics_settings()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  -- Raises for a name Postgres does not know.
  perform now() at time zone new.reporting_timezone;
  return new;
end;
$$;

create trigger analytics_settings_validate
before insert or update on public.analytics_settings
for each row execute function private.validate_analytics_settings();

insert into public.analytics_settings default values;

create function private.analytics_timezone()
returns text
language sql
stable
security definer
set search_path = ''
as $$ select s.reporting_timezone from public.analytics_settings s $$;

-- The reporting day an instant falls on (mirror of localDay in modules/analytics/dates.ts).
create function private.analytics_local_day(p_instant timestamptz)
returns date
language sql
stable
security definer
set search_path = ''
as $$ select (p_instant at time zone private.analytics_timezone())::date $$;

create function private.analytics_today()
returns date
language sql
stable
security definer
set search_path = ''
as $$ select private.analytics_local_day(now()) $$;

-- Raw events are kept for this many full reporting days, plus the current day.
create function private.analytics_raw_retention_days()
returns integer
language sql
immutable
set search_path = ''
as $$ select 7 $$;

-- Daily aggregates are kept for this many days (provisional). What a workspace SEES is the
-- analytics_days entitlement, which is smaller.
create function private.analytics_aggregate_retention_days()
returns integer
language sql
immutable
set search_path = ''
as $$ select 400 $$;

-- ---------------------------------------------------------------------------------------------
-- Raw events (append-only, short-lived)
-- ---------------------------------------------------------------------------------------------

create table public.analytics_events (
  profile_id uuid not null references public.profiles (id) on delete cascade,
  -- Generated by the visitor's browser (or by the database for form_submit); the deduplication key.
  event_id uuid not null,
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  -- Server clock at arrival. The client's clock is never trusted.
  occurred_at timestamptz not null default now(),
  -- Reporting day of occurred_at (private.analytics_local_day).
  day date not null,
  event_type public.analytics_event_type not null,
  -- Page-view dimensions: how the visit arrived. Null on every other event type.
  source public.analytics_source,
  device public.analytics_device,
  country text check (country is null or country ~ '^[A-Z]{2}$'),
  -- Id of the block in the live publication; null for page-level events.
  block_id text check (block_id is null or char_length(block_id) between 1 and 64),
  -- Salted daily HMAC of page + address + user agent; never the address. Null when the server has no salt.
  visitor_hash text check (visitor_hash is null or visitor_hash ~ '^[0-9a-f]{32}$'),
  utm_source text check (utm_source is null or utm_source ~ '^[a-z0-9_.-]{1,40}$'),
  utm_medium text check (utm_medium is null or utm_medium ~ '^[a-z0-9_.-]{1,40}$'),
  utm_campaign text check (utm_campaign is null or utm_campaign ~ '^[a-z0-9_.-]{1,40}$'),
  -- Also serves the page foreign key and deduplication (ignored on conflict).
  primary key (profile_id, event_id),
  constraint analytics_events_view_dimensions check (
    event_type = 'page_view'
    or (source is null and device is null and country is null and utm_source is null)
  ),
  constraint analytics_events_utm_needs_source check (
    utm_source is not null or (utm_medium is null and utm_campaign is null)
  )
);

-- Rate limits, the visit rule and the workspace foreign key.
create index analytics_events_workspace_profile_time_idx on public.analytics_events (workspace_id, profile_id, occurred_at);
-- Aggregation and purge go day by day.
create index analytics_events_day_idx on public.analytics_events (day);

comment on table public.analytics_events is
  'Raw customer-analytics events (ADR 0011). Append-only, written only by ingest_analytics_events and submit_form_lead, kept for private.analytics_raw_retention_days() days and then deleted by run_analytics_maintenance. Holds no IP address, user agent, referrer or URL: only enumerations, a salted daily hash and normalized UTM values. No client role can read it.';

-- ---------------------------------------------------------------------------------------------
-- Daily aggregates and the aggregation watermark
-- ---------------------------------------------------------------------------------------------

create table public.analytics_daily (
  profile_id uuid not null references public.profiles (id) on delete cascade,
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  day date not null,
  dimension public.analytics_dimension not null,
  event_type public.analytics_event_type not null,
  count integer not null check (count > 0),
  -- '' for total; block id; source; "utm_source|utm_medium|utm_campaign"; device; country.
  key text not null default '' check (char_length(key) <= 128),
  primary key (profile_id, day, dimension, key, event_type)
);

-- Consolidated dashboard (Sprint 7) and the workspace foreign key.
create index analytics_daily_workspace_day_idx on public.analytics_daily (workspace_id, day);
-- Retention purge.
create index analytics_daily_day_idx on public.analytics_daily (day);

comment on table public.analytics_daily is
  'Daily customer-analytics aggregates (ADR 0011): one count per page, reporting day, dimension, key and event type. Rebuilt per day by private.aggregate_analytics_day (delete + insert, idempotent). Read through get_profile_analytics, which applies the analytics_days entitlement. Aggregates only: no visitor-level data.';

create table public.analytics_day_status (
  day date primary key,
  aggregated_at timestamptz not null default now(),
  -- Set once the day is over and its aggregate is complete; only final days are purged from raw.
  finalized_at timestamptz,
  event_count integer not null default 0 check (event_count >= 0)
);

comment on table public.analytics_day_status is
  'Aggregation watermark (ADR 0011): one row per reporting day that was aggregated. The dashboard reads the latest final day to tell "consolidation is late" from "zero".';

alter table public.analytics_settings enable row level security;
alter table public.analytics_events enable row level security;
alter table public.analytics_daily enable row level security;
alter table public.analytics_day_status enable row level security;

-- No client role holds any table privilege and there are no policies: visitors write through
-- ingest_analytics_events, members read through get_profile_analytics, the job runs as the owner.
revoke all on public.analytics_settings, public.analytics_events, public.analytics_daily, public.analytics_day_status
  from public, anon, authenticated, service_role;
grant select on public.analytics_settings, public.analytics_events, public.analytics_daily, public.analytics_day_status to service_role;

-- ---------------------------------------------------------------------------------------------
-- Attestation (ADR 0011): only batches signed by the application server are stored
-- ---------------------------------------------------------------------------------------------

-- Shared secret between the application server (ANALYTICS_SIGNING_SECRET) and the database. Stored
-- in Supabase Vault under this name by a deploy step, never in a migration.
create function private.analytics_signing_secret()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select s.decrypted_secret from vault.decrypted_secrets s where s.name = 'analytics_signing_secret' limit 1;
$$;

create function private.analytics_is_configured()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$ select coalesce(char_length(private.analytics_signing_secret()) >= 32, false) $$;

-- True/false for a configured database; null when the secret is missing (nothing can be attested).
create function private.analytics_signature_is_valid(p_payload text, p_signature text)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_secret text := private.analytics_signing_secret();
  v_expected text;
begin
  if v_secret is null or char_length(v_secret) < 32 then
    return null;
  end if;
  if p_payload is null or p_signature is null or p_signature !~ '^[0-9a-f]{64}$' then
    return false;
  end if;
  v_expected := encode(extensions.hmac(convert_to(p_payload, 'UTF8'), convert_to(v_secret, 'UTF8'), 'sha256'), 'hex');
  -- Compare digests so the time taken does not depend on where the two strings differ.
  return extensions.digest(v_expected, 'sha256') = extensions.digest(p_signature, 'sha256');
end;
$$;

-- Block type an event must point at; null for page-level events (mirror of EVENT_BLOCK_TYPE).
create function private.analytics_event_block_type(p_type public.analytics_event_type)
returns text
language sql
immutable
set search_path = ''
as $$
  select case p_type
    when 'link_click' then 'link'
    when 'social_click' then 'social'
    when 'embed_load' then 'embed'
    when 'whatsapp_click' then 'whatsapp'
    when 'pix_copy' then 'pix'
    when 'pix_pay_click' then 'pix'
    when 'form_submit' then 'form'
  end;
$$;

-- Stored form of a UTM value (mirror of normalizeUtmValue's result).
create function private.analytics_utm_is_valid(p_value text)
returns boolean
language sql
immutable
set search_path = ''
as $$ select coalesce(p_value ~ '^[a-z0-9_.-]{1,40}$', false) $$;

-- First instant of a reporting day.
create function private.analytics_day_start(p_day date)
returns timestamptz
language sql
stable
security definer
set search_path = ''
as $$ select p_day::timestamp at time zone private.analytics_timezone() $$;

-- ---------------------------------------------------------------------------------------------
-- Ingestion (the only write path for visitors)
-- ---------------------------------------------------------------------------------------------

-- Stores a batch of events for one published page. `p_payload` is the JSON text built by the
-- application server (modules/analytics/attestation.ts) and `p_signature` its HMAC-SHA256:
--   {"v":1,"slug":"…","visitor":"<32 hex>"|null,
--    "view":{"source":"…","device":"…","country":"BR","utm_source":…,"utm_medium":…,"utm_campaign":…},
--    "events":[{"id":"<uuid>","type":"link_click","block":"<block id>"|null}]}
-- Answers {"status": …} and, for "ok", how many events were accepted, were duplicates of stored
-- events, were repeat views inside the visit window, were rejected or were rate limited. Safe to
-- retry: an event id is stored once per page.
--   not_configured  the signing secret is not in Vault
--   forbidden       missing or wrong signature (a direct call without the server)
--   invalid         malformed payload
--   unsupported     contract version this database does not know
--   unavailable     no published page at this address
create function public.ingest_analytics_events(p_payload text, p_signature text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_valid boolean;
  v_payload jsonb;
  v_slug text;
  v_profile public.profiles;
  v_document jsonb;
  v_blocks jsonb;
  v_view jsonb;
  v_visitor text;
  v_source public.analytics_source;
  v_device public.analytics_device;
  v_country text;
  v_utm_source text;
  v_utm_medium text;
  v_utm_campaign text;
  v_keep_utm boolean;
  v_event jsonb;
  v_type public.analytics_event_type;
  v_expected text;
  v_block text;
  v_day date;
  v_page_count integer;
  v_visitor_count integer;
  v_rows integer;
  v_accepted integer := 0;
  v_duplicate integer := 0;
  v_repeat integer := 0;
  v_rejected integer := 0;
  v_limited integer := 0;
begin
  if p_payload is null or octet_length(p_payload) > 8192 then
    return jsonb_build_object('status', 'invalid');
  end if;
  -- Before anything else: an unsigned caller learns nothing about pages or payloads.
  v_valid := private.analytics_signature_is_valid(p_payload, p_signature);
  if v_valid is null then
    return jsonb_build_object('status', 'not_configured');
  end if;
  if not v_valid then
    return jsonb_build_object('status', 'forbidden');
  end if;

  begin
    v_payload := p_payload::jsonb;
  exception when others then
    return jsonb_build_object('status', 'invalid');
  end;
  if jsonb_typeof(v_payload) <> 'object' then
    return jsonb_build_object('status', 'invalid');
  end if;
  if v_payload -> 'v' is distinct from '1'::jsonb then
    return jsonb_build_object('status', 'unsupported');
  end if;
  if jsonb_typeof(v_payload -> 'slug') is distinct from 'string'
    or jsonb_typeof(v_payload -> 'events') is distinct from 'array'
    or jsonb_array_length(v_payload -> 'events') not between 1 and 10 then
    return jsonb_build_object('status', 'invalid');
  end if;
  v_slug := v_payload ->> 'slug';
  if not private.slug_is_well_formed(v_slug) then
    return jsonb_build_object('status', 'unavailable');
  end if;

  -- Published, not deleted, in an active workspace: the same rule as submit_form_lead.
  select p.* into v_profile
  from public.profiles p
  join public.workspaces w on w.id = p.workspace_id
  where p.slug = v_slug
    and p.deleted_at is null
    and p.live_publication_id is not null
    and w.deleted_at is null
    and w.status = 'active';
  if not found then
    return jsonb_build_object('status', 'unavailable');
  end if;

  -- Blocks of the LIVE publication: {id: type}. An event can only name one of these.
  select pp.document into v_document from public.profile_publications pp where pp.id = v_profile.live_publication_id;
  select coalesce(jsonb_object_agg(b ->> 'id', b ->> 'type'), '{}'::jsonb) into v_blocks
  from jsonb_array_elements(case when jsonb_typeof(v_document -> 'blocks') = 'array' then v_document -> 'blocks' else '[]'::jsonb end) b
  where jsonb_typeof(b -> 'id') = 'string' and jsonb_typeof(b -> 'type') = 'string';
  -- A schema-version-1 snapshot shows its page-level social links as one row with a fixed id.
  if v_document ->> 'schemaVersion' = '1'
    and jsonb_typeof(v_document -> 'socialLinks') = 'array'
    and jsonb_array_length(v_document -> 'socialLinks') > 0 then
    v_blocks := v_blocks || jsonb_build_object('legacy-social', 'social');
  end if;

  v_visitor := case when jsonb_typeof(v_payload -> 'visitor') = 'string' and v_payload ->> 'visitor' ~ '^[0-9a-f]{32}$' then v_payload ->> 'visitor' end;

  v_view := case when jsonb_typeof(v_payload -> 'view') = 'object' then v_payload -> 'view' else '{}'::jsonb end;
  v_source := case when v_view ->> 'source' = any (enum_range(null::public.analytics_source)::text[]) then (v_view ->> 'source')::public.analytics_source end;
  v_device := case when v_view ->> 'device' = any (enum_range(null::public.analytics_device)::text[]) then (v_view ->> 'device')::public.analytics_device end;
  v_country := case when v_view ->> 'country' ~ '^[A-Z]{2}$' then v_view ->> 'country' else 'ZZ' end;
  v_utm_source := case when private.analytics_utm_is_valid(v_view ->> 'utm_source') then v_view ->> 'utm_source' end;
  if v_utm_source is not null then
    v_utm_medium := case when private.analytics_utm_is_valid(v_view ->> 'utm_medium') then v_view ->> 'utm_medium' end;
    v_utm_campaign := case when private.analytics_utm_is_valid(v_view ->> 'utm_campaign') then v_view ->> 'utm_campaign' end;
  end if;

  v_day := private.analytics_today();

  -- One batch at a time per page, so the counters below cannot be raced.
  perform pg_advisory_xact_lock(hashtextextended('analytics:' || v_profile.id::text, 0));

  -- Stored events only: what was rejected never counts against anybody.
  select count(*) into v_page_count
  from public.analytics_events e
  where e.workspace_id = v_profile.workspace_id and e.profile_id = v_profile.id
    and e.occurred_at > now() - interval '1 hour';
  -- Requests without a hash share one bucket per page. Server-side form events are not a visitor's.
  select count(*) into v_visitor_count
  from public.analytics_events e
  where e.workspace_id = v_profile.workspace_id and e.profile_id = v_profile.id
    and e.occurred_at > now() - interval '10 minutes'
    and e.visitor_hash is not distinct from v_visitor
    and e.event_type <> 'form_submit';

  for v_event in select value from jsonb_array_elements(v_payload -> 'events') loop
    -- form_submit is recorded by submit_form_lead when a lead is stored; nobody can send it.
    if jsonb_typeof(v_event) <> 'object'
      or jsonb_typeof(v_event -> 'id') is distinct from 'string'
      or (v_event ->> 'id') !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      or jsonb_typeof(v_event -> 'type') is distinct from 'string'
      or not (v_event ->> 'type' = any (enum_range(null::public.analytics_event_type)::text[]))
      or v_event ->> 'type' = 'form_submit' then
      v_rejected := v_rejected + 1;
      continue;
    end if;
    v_type := (v_event ->> 'type')::public.analytics_event_type;
    v_expected := private.analytics_event_block_type(v_type);
    v_block := case when jsonb_typeof(v_event -> 'block') = 'string' then v_event ->> 'block' end;

    if (v_expected is null and coalesce(jsonb_typeof(v_event -> 'block'), 'null') <> 'null')
      -- The block must be in the live publication and be of the type this event belongs to.
      or (v_expected is not null and (v_block is null or v_blocks ->> v_block is distinct from v_expected))
      or (v_type = 'page_view' and (v_source is null or v_device is null)) then
      v_rejected := v_rejected + 1;
      continue;
    end if;

    if exists (select 1 from public.analytics_events e where e.profile_id = v_profile.id and e.event_id = (v_event ->> 'id')::uuid) then
      v_duplicate := v_duplicate + 1;
      continue;
    end if;

    if v_page_count >= 2000 or v_visitor_count >= 30 then
      v_limited := v_limited + 1;
      continue;
    end if;

    -- Visit rule: a view from the same visitor within 30 minutes of a stored view is not a new visit.
    if v_type = 'page_view' and v_visitor is not null and exists (
      select 1 from public.analytics_events e
      where e.workspace_id = v_profile.workspace_id and e.profile_id = v_profile.id
        and e.occurred_at > now() - interval '30 minutes'
        and e.event_type = 'page_view' and e.visitor_hash = v_visitor
    ) then
      v_repeat := v_repeat + 1;
      continue;
    end if;

    -- Cardinality cap: at most 20 distinct UTM triples per page per day. Beyond that the view is
    -- still counted, without its UTM values.
    v_keep_utm := v_type = 'page_view' and v_utm_source is not null;
    if v_keep_utm and not exists (
      select 1 from public.analytics_events e
      where e.workspace_id = v_profile.workspace_id and e.profile_id = v_profile.id
        and e.occurred_at >= private.analytics_day_start(v_day)
        and e.utm_source = v_utm_source
        and e.utm_medium is not distinct from v_utm_medium
        and e.utm_campaign is not distinct from v_utm_campaign
    ) and (
      select count(*) from (
        select distinct e.utm_source, e.utm_medium, e.utm_campaign
        from public.analytics_events e
        where e.workspace_id = v_profile.workspace_id and e.profile_id = v_profile.id
          and e.occurred_at >= private.analytics_day_start(v_day)
          and e.utm_source is not null
      ) t
    ) >= 20 then
      v_keep_utm := false;
    end if;

    insert into public.analytics_events (
      profile_id, event_id, workspace_id, occurred_at, day, event_type, source, device, country, block_id, visitor_hash,
      utm_source, utm_medium, utm_campaign)
    values (
      v_profile.id, (v_event ->> 'id')::uuid, v_profile.workspace_id, now(), v_day, v_type,
      case when v_type = 'page_view' then v_source end,
      case when v_type = 'page_view' then v_device end,
      case when v_type = 'page_view' then v_country end,
      v_block, v_visitor,
      case when v_keep_utm then v_utm_source end,
      case when v_keep_utm then v_utm_medium end,
      case when v_keep_utm then v_utm_campaign end)
    on conflict (profile_id, event_id) do nothing;
    get diagnostics v_rows = row_count;
    if v_rows = 0 then
      v_duplicate := v_duplicate + 1;
    else
      v_accepted := v_accepted + 1;
      v_page_count := v_page_count + 1;
      v_visitor_count := v_visitor_count + 1;
    end if;
  end loop;

  return jsonb_build_object('status', 'ok', 'accepted', v_accepted, 'duplicate', v_duplicate, 'repeat', v_repeat,
    'rejected', v_rejected, 'rate_limited', v_limited);
end;
$$;

-- ---------------------------------------------------------------------------------------------
-- Form submission: the event is recorded where the lead is stored
-- ---------------------------------------------------------------------------------------------

-- Same function as Sprint 5 (signature, validation, limits and answers unchanged) plus one step:
-- when a lead is actually stored, a form_submit event is recorded in the same transaction. A retry
-- that is stored once produces one event. An analytics failure never fails the lead.
create or replace function public.submit_form_lead(
  p_slug text,
  p_block_id text,
  p_fields jsonb,
  p_consent boolean default false,
  p_honeypot text default '',
  p_client_hash text default null
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_slug text := private.normalize_slug(coalesce(p_slug, ''));
  v_profile public.profiles;
  v_document jsonb;
  v_version integer;
  v_form jsonb;
  v_field text;
  v_value text;
  v_name text;
  v_email text;
  v_phone text;
  v_message text;
  v_consent boolean := coalesce(p_consent, false);
  v_client text;
  v_dedupe text;
begin
  -- Hidden field real visitors never fill. Automated posts get the same answer as a real one.
  if btrim(coalesce(p_honeypot, '')) <> '' then
    return 'ok';
  end if;
  if not private.slug_is_well_formed(v_slug) or p_block_id is null then
    return 'unavailable';
  end if;
  if p_fields is null or jsonb_typeof(p_fields) <> 'object' or octet_length(p_fields::text) > 4096 then
    return 'invalid';
  end if;

  select p.* into v_profile
  from public.profiles p
  join public.workspaces w on w.id = p.workspace_id
  where p.slug = v_slug
    and p.deleted_at is null
    and p.live_publication_id is not null
    and w.deleted_at is null
    and w.status = 'active';
  if not found then
    return 'unavailable';
  end if;

  select pp.document, pp.version into v_document, v_version
  from public.profile_publications pp where pp.id = v_profile.live_publication_id;
  select b into v_form
  from jsonb_array_elements(case when jsonb_typeof(v_document -> 'blocks') = 'array' then v_document -> 'blocks' else '[]'::jsonb end) b
  where b ->> 'id' = p_block_id and b ->> 'type' = 'form'
  limit 1;
  if v_form is null or not private.is_valid_form_fields(v_form -> 'fields') then
    return 'unavailable';
  end if;

  -- Only the fields of the published form are read; anything else in the request is ignored.
  for v_field in select f from unnest(array['name', 'email', 'phone', 'message']) f where v_form -> 'fields' ? f loop
    v_value := case when jsonb_typeof(p_fields -> v_field) = 'string' then p_fields ->> v_field else '' end;
    if v_field = 'message' then
      v_value := btrim(regexp_replace(v_value, E'\r\n?', E'\n', 'g'), E' \t\n');
      if char_length(v_value) > 1000 or replace(v_value, E'\n', '') ~ '[[:cntrl:]]' then
        return 'invalid';
      end if;
      v_message := nullif(v_value, '');
    else
      v_value := regexp_replace(btrim(v_value, E' \t\n\r'), '\s+', ' ', 'g');
      if v_value = '' or v_value ~ '[[:cntrl:]]' then
        return 'invalid';
      end if;
      if v_field = 'name' then
        if char_length(v_value) > 100 then return 'invalid'; end if;
        v_name := v_value;
      elsif v_field = 'email' then
        v_value := lower(v_value);
        if char_length(v_value) > 254 or v_value !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then return 'invalid'; end if;
        v_email := v_value;
      else
        if char_length(v_value) > 20 or v_value !~ '^\+?[0-9[:space:]().-]+$' then return 'invalid'; end if;
        v_phone := case when v_value like '+%' then '+' else '' end || regexp_replace(v_value, '[^0-9]', '', 'g');
        if v_phone !~ '^\+?[0-9]{8,15}$' then return 'invalid'; end if;
      end if;
    end if;
  end loop;

  if coalesce((v_form ->> 'consentRequired')::boolean, true) and not v_consent then
    return 'consent_required';
  end if;

  -- One submission at a time per page, so the counters below cannot be raced.
  perform pg_advisory_xact_lock(hashtextextended('form_lead:' || v_profile.id::text, 0));

  delete from public.form_submission_hits h where h.profile_id = v_profile.id and h.created_at < now() - interval '1 day';
  delete from public.form_leads l where l.profile_id = v_profile.id and l.purge_after < now();

  -- Retry safety: the same content to the same form within 10 minutes is stored once.
  v_dedupe := md5(v_profile.id::text || ':' || p_block_id || ':' || coalesce(v_name, '') || E'\x1f' || coalesce(v_email, '') || E'\x1f' || coalesce(v_phone, '') || E'\x1f' || coalesce(v_message, ''));
  if exists (
    select 1 from public.form_leads l
    where l.profile_id = v_profile.id and l.dedupe_key = v_dedupe and l.created_at > now() - interval '10 minutes'
  ) then
    return 'ok';
  end if;

  -- A caller without a hash from the application (a direct API call) shares one bucket.
  v_client := case when p_client_hash ~ '^[0-9a-f]{32}$' then p_client_hash else 'direct' end;
  if (select count(*) from public.form_submission_hits h
      where h.profile_id = v_profile.id and h.client_hash = v_client and h.created_at > now() - interval '10 minutes') >= 5
    or (select count(*) from public.form_submission_hits h
        where h.profile_id = v_profile.id and h.created_at > now() - interval '1 hour') >= 60 then
    return 'rate_limited';
  end if;

  insert into public.form_submission_hits (profile_id, client_hash) values (v_profile.id, v_client);
  insert into public.form_leads (
    workspace_id, profile_id, block_id, publication_version, name, email, phone, message,
    consent_given, consent_required, consent_text, consent_version, consented_at, dedupe_key, purge_after)
  values (
    v_profile.workspace_id, v_profile.id, p_block_id, v_version, v_name, v_email, v_phone, v_message,
    v_consent, coalesce((v_form ->> 'consentRequired')::boolean, true), v_form ->> 'consentText', md5(v_form ->> 'consentText'),
    case when v_consent then now() end, v_dedupe, now() + private.lead_retention());

  -- Customer analytics (ADR 0011): the one place a form_submit event is created. It carries no
  -- visitor hash and nothing of what was typed. Never allowed to fail the lead.
  begin
    insert into public.analytics_events (profile_id, event_id, workspace_id, occurred_at, day, event_type, block_id)
    values (v_profile.id, gen_random_uuid(), v_profile.workspace_id, now(), private.analytics_today(), 'form_submit', p_block_id);
  exception when others then
    null;
  end;
  return 'ok';
end;
$$;

-- ---------------------------------------------------------------------------------------------
-- Aggregation, watermark and purge (the job)
-- ---------------------------------------------------------------------------------------------

-- Counts of raw events per day, dimension, key and type: the single definition used both to build
-- the daily aggregate and to read days that are not final yet.
create function private.analytics_counts(p_profile_id uuid, p_from date, p_to date)
returns table (
  workspace_id uuid,
  profile_id uuid,
  day date,
  dimension public.analytics_dimension,
  key text,
  event_type public.analytics_event_type,
  count integer
)
language sql
stable
security definer
set search_path = ''
as $$
  with e as materialized (
    select ev.workspace_id, ev.profile_id, ev.day, ev.event_type, ev.block_id, ev.source, ev.device, ev.country,
      ev.utm_source, ev.utm_medium, ev.utm_campaign
    from public.analytics_events ev
    where ev.day between p_from and p_to
      and (p_profile_id is null or ev.profile_id = p_profile_id)
  )
  select e.workspace_id, e.profile_id, e.day, 'total'::public.analytics_dimension, '', e.event_type, count(*)::integer
  from e group by e.workspace_id, e.profile_id, e.day, e.event_type
  union all
  select e.workspace_id, e.profile_id, e.day, 'block', e.block_id, e.event_type, count(*)::integer
  from e where e.block_id is not null group by e.workspace_id, e.profile_id, e.day, e.block_id, e.event_type
  union all
  select e.workspace_id, e.profile_id, e.day, 'source', e.source::text, e.event_type, count(*)::integer
  from e where e.event_type = 'page_view' and e.source is not null group by e.workspace_id, e.profile_id, e.day, e.source, e.event_type
  union all
  select e.workspace_id, e.profile_id, e.day, 'utm', e.utm_source || '|' || coalesce(e.utm_medium, '') || '|' || coalesce(e.utm_campaign, ''), e.event_type, count(*)::integer
  from e where e.event_type = 'page_view' and e.utm_source is not null
  group by e.workspace_id, e.profile_id, e.day, e.utm_source, e.utm_medium, e.utm_campaign, e.event_type
  union all
  select e.workspace_id, e.profile_id, e.day, 'device', e.device::text, e.event_type, count(*)::integer
  from e where e.event_type = 'page_view' and e.device is not null group by e.workspace_id, e.profile_id, e.day, e.device, e.event_type
  union all
  select e.workspace_id, e.profile_id, e.day, 'country', e.country, e.event_type, count(*)::integer
  from e where e.event_type = 'page_view' and e.country is not null group by e.workspace_id, e.profile_id, e.day, e.country, e.event_type;
$$;

-- Rebuilds the aggregate of one day from its raw events. Replacement, not accumulation: running it
-- again gives the same rows. A day before today becomes final.
create function private.aggregate_analytics_day(p_day date)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_rows integer;
begin
  delete from public.analytics_daily d where d.day = p_day;
  insert into public.analytics_daily (workspace_id, profile_id, day, dimension, key, event_type, count)
  select c.workspace_id, c.profile_id, c.day, c.dimension, c.key, c.event_type, c.count
  from private.analytics_counts(null, p_day, p_day) c;
  get diagnostics v_rows = row_count;

  insert into public.analytics_day_status (day, aggregated_at, finalized_at, event_count)
  values (p_day, now(), case when p_day < private.analytics_today() then now() end,
    (select count(*) from public.analytics_events e where e.day = p_day))
  on conflict (day) do update
  set aggregated_at = excluded.aggregated_at,
    event_count = excluded.event_count,
    finalized_at = coalesce(public.analytics_day_status.finalized_at, excluded.finalized_at);
  return v_rows;
end;
$$;

-- The scheduled job (service role only). Aggregates every day that is not final yet, up to today
-- (at most 10 days per run), then deletes raw events older than the retention for days that are
-- final (at most 50,000 rows per run) and aggregates past their own retention. Safe to repeat.
-- With `p_day`, only re-aggregates that day, which must still have its raw events.
create function public.run_analytics_maintenance(p_day date default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_today date := private.analytics_today();
  v_raw_floor date := v_today - private.analytics_raw_retention_days();
  v_start date;
  v_day date;
  v_days integer := 0;
  v_rows integer := 0;
  v_purged_events integer := 0;
  v_purged_aggregates integer := 0;
begin
  -- One run at a time.
  perform pg_advisory_xact_lock(hashtextextended('analytics:maintenance', 0));

  if p_day is not null then
    if p_day > v_today or p_day < v_raw_floor then
      return jsonb_build_object('status', 'out_of_range', 'today', v_today, 'oldest_raw_day', v_raw_floor);
    end if;
    v_rows := private.aggregate_analytics_day(p_day);
    return jsonb_build_object('status', 'ok', 'aggregated_days', 1, 'aggregate_rows', v_rows, 'purged_events', 0,
      'purged_aggregate_rows', 0, 'pending_days', 0,
      'last_final_day', (select max(s.day) from public.analytics_day_status s where s.finalized_at is not null));
  end if;

  -- First day that is not final: the day after the watermark, or the first day that has events.
  select coalesce(
    (select max(s.day) + 1 from public.analytics_day_status s where s.finalized_at is not null),
    (select min(e.day) from public.analytics_events e),
    v_today) into v_start;

  v_day := v_start;
  while v_day <= v_today and v_days < 10 loop
    v_rows := v_rows + private.aggregate_analytics_day(v_day);
    v_days := v_days + 1;
    v_day := v_day + 1;
  end loop;

  -- Raw events are deleted only after their day is final, so a job that was down loses nothing.
  delete from public.analytics_events e
  where e.ctid in (
    select ev.ctid
    from public.analytics_events ev
    join public.analytics_day_status s on s.day = ev.day and s.finalized_at is not null
    where ev.day < v_raw_floor
    limit 50000);
  get diagnostics v_purged_events = row_count;

  delete from public.analytics_daily d where d.day < v_today - private.analytics_aggregate_retention_days();
  get diagnostics v_purged_aggregates = row_count;
  delete from public.analytics_day_status s where s.day < v_today - private.analytics_aggregate_retention_days();

  return jsonb_build_object('status', 'ok', 'aggregated_days', v_days, 'aggregate_rows', v_rows,
    'purged_events', v_purged_events, 'purged_aggregate_rows', v_purged_aggregates,
    -- Days still waiting because of the per-run bound; the next run continues.
    'pending_days', greatest(0, v_today - v_day + 1),
    'last_final_day', (select max(s.day) from public.analytics_day_status s where s.finalized_at is not null));
end;
$$;

-- ---------------------------------------------------------------------------------------------
-- Dashboard read (members) and export audit
-- ---------------------------------------------------------------------------------------------

-- Report of one page for a window of reporting days. Final days come from analytics_daily; days
-- that are not final yet (normally only today) are counted from that page's raw events, so the
-- dashboard does not wait for the nightly job. The window is clamped to today and to the history
-- depth of the workspace's plan (the analytics_days entitlement). One JSON object, bounded:
-- at most 400 days x 9 types of daily totals, the page's blocks, 12 sources, 4 device classes and
-- the 20 largest UTM triples and countries.
create function public.get_profile_analytics(p_profile_id uuid, p_from date, p_to date)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_profile public.profiles;
  v_today date := private.analytics_today();
  v_history integer;
  v_from date;
  v_to date;
  v_last_final date;
  v_live_from date;
  v_result jsonb;
begin
  if (select auth.uid()) is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  select p.* into v_profile from public.profiles p where p.id = p_profile_id and p.deleted_at is null;
  -- Matrix: analytics.view = owner, admin, editor, that is, every member (modules/identity/permissions.ts).
  if not found or private.workspace_role(v_profile.workspace_id) is null then
    raise exception 'profile not found' using errcode = 'P0002';
  end if;
  if p_from is null or p_to is null or p_from > p_to then
    raise exception 'invalid window' using errcode = '22023';
  end if;

  v_history := least(greatest(coalesce(private.entitlement_int(v_profile.workspace_id, 'analytics_days'), 0), 1),
    private.analytics_aggregate_retention_days());
  v_to := least(p_to, v_today);
  v_from := least(greatest(p_from, v_today - (v_history - 1)), v_to);

  select max(s.day) into v_last_final from public.analytics_day_status s where s.finalized_at is not null;
  v_live_from := greatest(v_from, coalesce(v_last_final + 1, v_from));

  with counts as materialized (
    select d.day, d.dimension, d.key, d.event_type, d.count
    from public.analytics_daily d
    where d.profile_id = v_profile.id and d.day between v_from and v_to and d.day < v_live_from
    union all
    select c.day, c.dimension, c.key, c.event_type, c.count
    from private.analytics_counts(v_profile.id, v_live_from, v_to) c
  )
  select jsonb_build_object(
    'days', coalesce((
      select jsonb_agg(jsonb_build_object('day', t.day, 'event_type', t.event_type, 'count', t.total) order by t.day, t.event_type)
      from (select c.day, c.event_type, sum(c.count)::integer as total from counts c where c.dimension = 'total' group by c.day, c.event_type) t), '[]'::jsonb),
    'blocks', coalesce((
      select jsonb_agg(jsonb_build_object('block_id', t.key, 'event_type', t.event_type, 'count', t.total) order by t.total desc, t.key, t.event_type)
      from (select c.key, c.event_type, sum(c.count)::integer as total from counts c where c.dimension = 'block' group by c.key, c.event_type) t), '[]'::jsonb),
    'sources', coalesce((
      select jsonb_agg(jsonb_build_object('key', t.key, 'count', t.total) order by t.total desc, t.key)
      from (select c.key, sum(c.count)::integer as total from counts c where c.dimension = 'source' group by c.key) t), '[]'::jsonb),
    'utms', coalesce((
      select jsonb_agg(jsonb_build_object('key', t.key, 'count', t.total) order by t.total desc, t.key)
      from (select c.key, sum(c.count)::integer as total from counts c where c.dimension = 'utm' group by c.key order by 2 desc, 1 limit 20) t), '[]'::jsonb),
    'devices', coalesce((
      select jsonb_agg(jsonb_build_object('key', t.key, 'count', t.total) order by t.total desc, t.key)
      from (select c.key, sum(c.count)::integer as total from counts c where c.dimension = 'device' group by c.key) t), '[]'::jsonb),
    'countries', coalesce((
      select jsonb_agg(jsonb_build_object('key', t.key, 'count', t.total) order by t.total desc, t.key)
      from (select c.key, sum(c.count)::integer as total from counts c where c.dimension = 'country' group by c.key order by 2 desc, 1 limit 20) t), '[]'::jsonb)
  ) into v_result;

  return v_result || jsonb_build_object(
    'timezone', private.analytics_timezone(),
    'today', v_today,
    'from', v_from,
    'to', v_to,
    'history_days', v_history,
    'configured', private.analytics_is_configured(),
    -- The first day this page could have data.
    'collecting_since', greatest(
      private.analytics_local_day(v_profile.created_at),
      (select private.analytics_local_day(s.collection_started_at) from public.analytics_settings s)),
    -- Across the whole retained history, not only the window: "never had data" is not "zero here".
    'first_event_day', least(
      (select min(d.day) from public.analytics_daily d where d.profile_id = v_profile.id),
      (select min(e.day) from public.analytics_events e where e.profile_id = v_profile.id)),
    'last_final_day', v_last_final);
end;
$$;

-- Called by the application right before it hands the CSV to the person.
create function public.record_analytics_export(p_profile_id uuid, p_from date, p_to date, p_rows integer)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_workspace_id uuid;
begin
  if (select auth.uid()) is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  select p.workspace_id into v_workspace_id from public.profiles p where p.id = p_profile_id and p.deleted_at is null;
  -- Matrix: analytics.export = owner, admin, editor (aggregates only; no visitor data).
  if not found or private.workspace_role(v_workspace_id) is null then
    raise exception 'profile not found' using errcode = 'P0002';
  end if;
  perform private.write_audit_event(v_workspace_id, 'analytics.exported', 'profile', p_profile_id,
    jsonb_build_object('from', p_from, 'to', p_to, 'rows', greatest(0, coalesce(p_rows, 0))));
end;
$$;

-- ---------------------------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------------------------

revoke all on all functions in schema private from public, anon, authenticated;
grant execute on function
  private.member_workspace_ids(),
  private.writable_workspace_ids(public.workspace_role[]),
  private.workspace_ids_with_role(public.workspace_role[])
to authenticated;

revoke all on function
  public.ingest_analytics_events(text, text),
  public.run_analytics_maintenance(date),
  public.get_profile_analytics(uuid, date, date),
  public.record_analytics_export(uuid, date, date, integer)
from public, anon, authenticated, service_role;

-- Visitors' events arrive through the application server acting as anon; a signed-in person's
-- request would be dropped by the server, but the grant keeps the RPC callable with either key.
grant execute on function public.ingest_analytics_events(text, text) to anon, authenticated;

grant execute on function
  public.get_profile_analytics(uuid, date, date),
  public.record_analytics_export(uuid, date, date, integer)
to authenticated;

-- The job is administrative, never a user action.
grant execute on function public.run_analytics_maintenance(date) to service_role;
