-- Sprint 5: media (attested uploads, quota, lifecycle), themes, the image/embed/pix/form blocks and
-- form leads. Design: docs/adr/0009-media-and-storage-adapter.md and
-- docs/adr/0010-themes-templates-and-new-blocks.md.
-- Forward-only and additive: the Sprint 4 application keeps working against this schema (it ignores
-- the new column, block types and tables). The snapshot stays at schema version 2.
-- SQLSTATEs (ADR 0004 contract, extended): LK010 entitlement exceeded (detail storage_mb),
-- LK040 invalid draft content, LK060 upload not attested by the application, LK061 upload rate
-- limit, LK062 stored objects do not match the registration, LK090 media signing not configured,
-- 42501 forbidden, P0002 not found.
-- Mirrors: apps/web/src/modules/blocks/*, modules/themes/tokens.ts, modules/media/*, modules/leads/*.

-- ---------------------------------------------------------------------------------------------
-- Storage quota entitlement
-- ---------------------------------------------------------------------------------------------

alter table public.plan_entitlements drop constraint plan_entitlements_typed_value;
alter table public.plan_entitlements add constraint plan_entitlements_typed_value check (
  case
    when key in ('max_profiles', 'analytics_days', 'team_members', 'storage_mb')
      then int_value is not null and bool_value is null
    else bool_value is not null and int_value is null
  end
);

-- Megabytes of stored media per workspace (commercial hypotheses, mirror of lib/product.ts).
insert into public.plan_entitlements (plan_id, key, int_value, bool_value) values
  ('free', 'storage_mb', 20, null),
  ('pro', 'storage_mb', 100, null),
  ('agency', 'storage_mb', 500, null);

-- ---------------------------------------------------------------------------------------------
-- Media assets
-- ---------------------------------------------------------------------------------------------

create type public.media_kind as enum ('avatar', 'image');
create type public.media_status as enum ('pending', 'ready', 'failed', 'deleting');

create table public.media_assets (
  -- Also the storage key prefix: objects are "<id>/<width>.webp". Random, generated by the server.
  id uuid primary key,
  -- Restrict, not cascade: a workspace or page cannot be purged while it still owns objects.
  workspace_id uuid not null references public.workspaces (id) on delete restrict,
  profile_id uuid not null references public.profiles (id) on delete restrict,
  kind public.media_kind not null,
  status public.media_status not null default 'pending',
  -- Dimensions of the master (largest) variant.
  width integer not null check (width between 1 and 4096),
  height integer not null check (height between 1 and 4096),
  -- Sum of all variants.
  bytes integer not null check (bytes between 1 and 8388608),
  content_type text not null default 'image/webp' check (content_type = 'image/webp'),
  -- [{w, h, bytes}], validated by private.media_variants_are_valid.
  variants jsonb not null check (jsonb_typeof(variants) = 'array' and jsonb_array_length(variants) between 1 and 4),
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  activated_at timestamptz,
  constraint media_assets_ready_is_activated check (status <> 'ready' or activated_at is not null)
);

create index media_assets_workspace_idx on public.media_assets (workspace_id);
create index media_assets_profile_idx on public.media_assets (profile_id);
create index media_assets_created_by_idx on public.media_assets (created_by) where created_by is not null;
-- Cleanup scans by state and age.
create index media_assets_status_created_idx on public.media_assets (status, created_at);

comment on table public.media_assets is
  'Uploaded images (ADR 0009). One row per asset; objects live in the "media" bucket under "<id>/<width>.webp". An asset is kept while the page draft or a retained publication references it (private.media_is_referenced) and removed by the cleanup job otherwise. May show people and places; EXIF/GPS metadata is stripped before storage.';

-- Grace periods (mirror of modules/media/references.ts).
create function private.media_pending_grace()
returns interval
language sql
immutable
set search_path = ''
as $$ select interval '1 hour' $$;

create function private.media_orphan_grace()
returns interval
language sql
immutable
set search_path = ''
as $$ select interval '24 hours' $$;

-- True while the page's draft or any retained publication of the page points at the asset.
-- Computed from the documents, so there is no second source of truth to drift.
create function private.media_is_referenced(p_media_id uuid, p_profile_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
      select 1 from public.profiles p
      where p.id = p_profile_id
        and (p.avatar_path = p_media_id::text
          or p.blocks @> jsonb_build_array(jsonb_build_object('type', 'image', 'mediaId', p_media_id::text)))
    )
    or exists (
      select 1 from public.profile_publications pp
      where pp.profile_id = p_profile_id
        and (pp.document ->> 'avatarPath' = p_media_id::text
          or pp.document -> 'blocks' @> jsonb_build_array(jsonb_build_object('type', 'image', 'mediaId', p_media_id::text)))
    );
$$;

-- Bytes that count against the quota: live assets that are referenced or still inside the grace
-- period. Orphans stop counting as soon as they are cleanup candidates.
create function private.workspace_media_bytes(p_workspace_id uuid)
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(sum(m.bytes), 0)::bigint
  from public.media_assets m
  where m.workspace_id = p_workspace_id
    and m.status in ('pending', 'ready')
    and (m.created_at > now() - private.media_orphan_grace() or private.media_is_referenced(m.id, m.profile_id));
$$;

-- Variant plan (mirror of modules/media/policy.ts planVariants): avatars are the three squares;
-- images keep 448/896/1344 below the master width plus the master itself, never enlarged.
create function private.media_variants_are_valid(p_kind public.media_kind, p_width integer, p_height integer, p_variants jsonb)
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_widths integer[];
  v_expected integer[];
begin
  if p_kind is null or p_width is null or p_height is null
    or p_variants is null or jsonb_typeof(p_variants) <> 'array'
    or jsonb_array_length(p_variants) not between 1 and 4 then
    return false;
  end if;
  if exists (
    select 1 from jsonb_array_elements(p_variants) v
    where jsonb_typeof(v) <> 'object'
      or (select array_agg(k order by k collate "C") from jsonb_object_keys(v) k) is distinct from array['bytes', 'h', 'w']
      or jsonb_typeof(v -> 'w') <> 'number' or (v ->> 'w') !~ '^[1-9][0-9]{0,3}$'
      or jsonb_typeof(v -> 'h') <> 'number' or (v ->> 'h') !~ '^[1-9][0-9]{0,3}$'
      or jsonb_typeof(v -> 'bytes') <> 'number' or (v ->> 'bytes') !~ '^[1-9][0-9]{0,6}$'
      or (v ->> 'bytes')::integer > 2097152
  ) then
    return false;
  end if;

  select array_agg((v ->> 'w')::integer order by (v ->> 'w')::integer) into v_widths from jsonb_array_elements(p_variants) v;
  if p_kind = 'avatar' then
    v_expected := array[96, 192, 288];
    if p_width <> 288 or p_height <> 288
      or exists (select 1 from jsonb_array_elements(p_variants) v where v ->> 'w' <> v ->> 'h') then
      return false;
    end if;
  else
    if p_width not between 200 and 1344 or p_height not between 100 and 4096
      or p_width > 3 * p_height or p_height > 3 * p_width then
      return false;
    end if;
    v_expected := array(select w from unnest(array[448, 896, 1344]) w where w < p_width order by w) || p_width;
  end if;
  if v_widths is distinct from v_expected then
    return false;
  end if;
  -- The master variant carries the declared dimensions.
  return exists (
    select 1 from jsonb_array_elements(p_variants) v
    where (v ->> 'w')::integer = p_width and (v ->> 'h')::integer = p_height
  );
end;
$$;

-- Canonical text the application signs (mirror of modules/media/attestation.ts registerPayload).
create function private.media_register_payload(p_media_id uuid, p_profile_id uuid, p_kind public.media_kind, p_width integer, p_height integer, p_variants jsonb)
returns text
language sql
immutable
set search_path = ''
as $$
  select 'register:' || p_media_id::text || ':' || p_profile_id::text || ':' || p_kind::text || ':' || p_width::text || 'x' || p_height::text || ':'
    || (select string_agg((v ->> 'w') || 'x' || (v ->> 'h') || 'x' || (v ->> 'bytes'), ',' order by (v ->> 'w')::integer)
        from jsonb_array_elements(p_variants) v);
$$;

-- Shared secret between the application server (MEDIA_SIGNING_SECRET) and the database. Stored in
-- Supabase Vault under this name by a deploy step, never in a migration.
create function private.media_signing_secret()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select s.decrypted_secret from vault.decrypted_secrets s where s.name = 'media_signing_secret' limit 1;
$$;

-- HMAC-SHA256 attestation (ADR 0009): proves the caller is the application server that validated
-- and re-encoded the bytes, not just somebody with a valid session.
create function private.media_signature_is_valid(p_payload text, p_signature text)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_secret text := private.media_signing_secret();
  v_expected text;
begin
  if v_secret is null or char_length(v_secret) < 32 then
    raise exception 'media signing is not configured' using errcode = 'LK090';
  end if;
  if p_payload is null or p_signature is null or p_signature !~ '^[0-9a-f]{64}$' then
    return false;
  end if;
  v_expected := encode(extensions.hmac(convert_to(p_payload, 'UTF8'), convert_to(v_secret, 'UTF8'), 'sha256'), 'hex');
  -- Compare digests so the time taken does not depend on where the two strings differ.
  return extensions.digest(v_expected, 'sha256') = extensions.digest(p_signature, 'sha256');
end;
$$;

-- Step 1 of an upload: the server registers what it validated. Called as the signed-in user.
create function public.register_media_asset(
  p_media_id uuid,
  p_profile_id uuid,
  p_kind public.media_kind,
  p_width integer,
  p_height integer,
  p_variants jsonb,
  p_signature text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_profile public.profiles;
  v_role public.workspace_role;
  v_bytes bigint;
  v_limit bigint;
  v_recent integer;
begin
  if v_uid is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  select p.* into v_profile from public.profiles p where p.id = p_profile_id and p.deleted_at is null;
  if not found then
    raise exception 'profile not found' using errcode = 'P0002';
  end if;
  v_role := private.workspace_role(v_profile.workspace_id);
  if v_role is null then
    raise exception 'profile not found' using errcode = 'P0002';
  end if;
  if not private.workspace_is_writable(v_profile.workspace_id) then
    raise exception 'workspace does not accept changes' using errcode = '42501';
  end if;
  -- Matrix: profile.edit_content = owner, admin, editor (modules/identity/permissions.ts).
  if v_role not in ('owner', 'admin', 'editor') then
    raise exception 'role cannot upload media' using errcode = '42501';
  end if;

  if p_media_id is null or not private.media_variants_are_valid(p_kind, p_width, p_height, p_variants) then
    raise exception 'invalid media description' using errcode = '22023';
  end if;
  if not private.media_signature_is_valid(
    private.media_register_payload(p_media_id, p_profile_id, p_kind, p_width, p_height, p_variants), p_signature) then
    raise exception 'upload was not validated by the application' using errcode = 'LK060';
  end if;

  -- Lock the workspace so concurrent uploads cannot both pass the quota.
  perform 1 from public.workspaces w where w.id = v_profile.workspace_id for update;

  select count(*) into v_recent
  from public.media_assets m
  where m.workspace_id = v_profile.workspace_id and m.created_at > now() - interval '1 hour';
  if v_recent >= 60 then
    raise exception 'too many uploads' using errcode = 'LK061';
  end if;

  select sum((v ->> 'bytes')::bigint) into v_bytes from jsonb_array_elements(p_variants) v;
  v_limit := coalesce(private.entitlement_int(v_profile.workspace_id, 'storage_mb'), 0)::bigint * 1048576;
  if private.workspace_media_bytes(v_profile.workspace_id) + v_bytes > v_limit then
    raise exception 'storage quota reached' using errcode = 'LK010', detail = 'storage_mb';
  end if;

  insert into public.media_assets (id, workspace_id, profile_id, kind, status, width, height, bytes, variants, created_by)
  values (p_media_id, v_profile.workspace_id, v_profile.id, p_kind, 'pending', p_width, p_height, v_bytes::integer, p_variants, v_uid);
end;
$$;

-- Step 3 of an upload: every registered variant is in the bucket with the registered size.
create function public.activate_media_asset(p_media_id uuid, p_signature text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_asset public.media_assets;
  v_stored integer;
begin
  if v_uid is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  select m.* into v_asset from public.media_assets m where m.id = p_media_id for update;
  if not found or v_asset.created_by is distinct from v_uid then
    raise exception 'media not found' using errcode = 'P0002';
  end if;
  if v_asset.status = 'ready' then
    return;
  end if;
  if v_asset.status <> 'pending' then
    raise exception 'media cannot be activated' using errcode = '42501';
  end if;
  if not private.media_signature_is_valid('activate:' || p_media_id::text, p_signature) then
    raise exception 'upload was not validated by the application' using errcode = 'LK060';
  end if;

  select count(*) into v_stored
  from jsonb_array_elements(v_asset.variants) v
  join storage.objects o
    on o.bucket_id = 'media'
   and o.name = p_media_id::text || '/' || (v ->> 'w') || '.webp'
   and o.metadata ->> 'size' = v ->> 'bytes';
  if v_stored <> jsonb_array_length(v_asset.variants) then
    raise exception 'stored objects do not match the registration' using errcode = 'LK062';
  end if;

  update public.media_assets set status = 'ready', activated_at = now() where id = p_media_id;
end;
$$;

-- The uploader abandons its own pending asset; cleanup removes whatever was written.
create function public.fail_media_asset(p_media_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  update public.media_assets
  set status = 'failed'
  where id = p_media_id and created_by = (select auth.uid()) and status = 'pending';
end;
$$;

-- "Espaço usado" for the editor.
create function public.workspace_storage_usage(p_workspace_id uuid)
returns table (used_bytes bigint, limit_bytes bigint)
language plpgsql
stable
security definer
set search_path = ''
as $$
#variable_conflict use_column
begin
  if (select auth.uid()) is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  if p_workspace_id is null or p_workspace_id not in (select private.member_workspace_ids()) then
    raise exception 'workspace not found' using errcode = 'P0002';
  end if;
  used_bytes := private.workspace_media_bytes(p_workspace_id);
  limit_bytes := coalesce(private.entitlement_int(p_workspace_id, 'storage_mb'), 0)::bigint * 1048576;
  return next;
end;
$$;

-- Cleanup, step 1 (service role only): candidates become `deleting` and are returned with their
-- object names. The page row is locked and references are re-checked, so an asset a concurrent
-- save or publish just started using is never claimed. Safe to call again at any time.
create function public.claim_media_cleanup(p_limit integer default 50)
returns table (media_id uuid, object_names text[])
language plpgsql
security definer
set search_path = ''
as $$
#variable_conflict use_column
declare
  v_row record;
begin
  for v_row in
    select m.id, m.profile_id
    from public.media_assets m
    where m.status = 'deleting'
      or (m.status in ('pending', 'failed') and m.created_at < now() - private.media_pending_grace())
      or (m.status = 'ready' and m.created_at < now() - private.media_orphan_grace()
          and not private.media_is_referenced(m.id, m.profile_id))
      or exists (select 1 from public.profiles p where p.id = m.profile_id and p.purge_after < now())
    order by m.created_at
    limit greatest(1, least(coalesce(p_limit, 50), 200))
  loop
    perform 1 from public.profiles p where p.id = v_row.profile_id for update;
    update public.media_assets m
    set status = 'deleting'
    where m.id = v_row.id
      and (
        m.status in ('deleting', 'pending', 'failed')
        or exists (select 1 from public.profiles p where p.id = m.profile_id and p.purge_after < now())
        or not private.media_is_referenced(m.id, m.profile_id)
      );
    if found then
      media_id := v_row.id;
      select array_agg(v_row.id::text || '/' || (v ->> 'w') || '.webp' order by (v ->> 'w')::integer) into object_names
      from public.media_assets m, jsonb_array_elements(m.variants) v
      where m.id = v_row.id;
      return next;
    end if;
  end loop;
end;
$$;

-- Cleanup, step 2 (service role only): the objects are gone, forget the rows.
create function public.finish_media_cleanup(p_media_ids uuid[])
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  delete from public.media_assets m where m.id = any (p_media_ids) and m.status = 'deleting';
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

alter table public.media_assets enable row level security;
revoke all on public.media_assets from public, anon, authenticated, service_role;

-- Members see the assets of their workspaces; every write goes through the RPCs above.
grant select on public.media_assets to authenticated, service_role;

create policy media_assets_select_member on public.media_assets
for select to authenticated
using (workspace_id in (select private.member_workspace_ids()));

-- ---------------------------------------------------------------------------------------------
-- Storage bucket and policies
-- ---------------------------------------------------------------------------------------------

-- Public read by URL (pages are public), WebP only, 2 MiB per object. Nothing can be listed: there
-- is no select policy on storage.objects.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('media', 'media', true, 2097152, array['image/webp'])
on conflict (id) do update
set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

-- The only way a user token can write to storage: the object is a variant of a pending asset that
-- the same person registered (which needed the application's signature). A direct upload with a
-- valid session but no registration matches nothing and is rejected. There is no update or delete
-- policy; cleanup runs with the service role.
create policy media_objects_insert_registered on storage.objects
for insert to authenticated
with check (
  bucket_id = 'media'
  and exists (
    select 1
    from public.media_assets m
    where m.status = 'pending'
      and m.created_by = (select auth.uid())
      and objects.name in (
        select m.id::text || '/' || (v ->> 'w') || '.webp' from jsonb_array_elements(m.variants) v
      )
  )
);

-- ---------------------------------------------------------------------------------------------
-- Theme (draft) and field rules for the new block types
-- ---------------------------------------------------------------------------------------------

alter table public.profiles
  add column theme jsonb check (theme is null or (jsonb_typeof(theme) = 'object' and pg_column_size(theme) <= 1024));

comment on column public.profiles.theme is
  'Draft theme tokens (ADR 0010): background, button, buttonStyle, corners, spacing, font. Null is the classic look. Validated by private.is_valid_theme (mirror of modules/themes/tokens.ts).';
comment on column public.profiles.avatar_path is
  'Draft avatar: id of a ready avatar asset of this page (public.media_assets), or null for the initials. Never a URL or inline data.';
comment on column public.profiles.blocks is
  'Draft blocks (ADR 0008/0010): link, text, social, whatsapp, divider, image, embed, pix, form. Validated by private.validate_profile_draft (mirror of modules/blocks).';

-- Closed token set: two lowercase hex colors and four enumerations, nothing else.
create function private.is_valid_theme(p_theme jsonb)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select coalesce(
    jsonb_typeof(p_theme) = 'object'
    and (select array_agg(k order by k collate "C") from jsonb_object_keys(p_theme) k)
      = array['background', 'button', 'buttonStyle', 'corners', 'font', 'spacing']
    and jsonb_typeof(p_theme -> 'background') = 'string' and p_theme ->> 'background' ~ '^#[0-9a-f]{6}$'
    and jsonb_typeof(p_theme -> 'button') = 'string' and p_theme ->> 'button' ~ '^#[0-9a-f]{6}$'
    and jsonb_typeof(p_theme -> 'buttonStyle') = 'string' and p_theme ->> 'buttonStyle' in ('filled', 'outline', 'soft')
    and jsonb_typeof(p_theme -> 'corners') = 'string' and p_theme ->> 'corners' in ('square', 'rounded', 'pill')
    and jsonb_typeof(p_theme -> 'spacing') = 'string' and p_theme ->> 'spacing' in ('compact', 'regular', 'relaxed')
    and jsonb_typeof(p_theme -> 'font') = 'string' and p_theme ->> 'font' in ('system', 'serif', 'poppins', 'lora'),
    false);
$$;

-- Embed allowlist: a provider id and a resource id in the provider's own format. No URL, no markup.
create function private.is_valid_embed_ref(p_provider text, p_ref text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select coalesce(case p_provider
    when 'youtube' then p_ref ~ '^[A-Za-z0-9_-]{11}$'
    when 'vimeo' then p_ref ~ '^[0-9]{6,12}$'
    when 'spotify' then p_ref ~ '^(?:track|album|playlist|episode|show|artist)/[A-Za-z0-9]{22}$'
  end, false);
$$;

create function private.mod11_check_digit(p_digits text, p_weights integer[])
returns integer
language sql
immutable
set search_path = ''
as $$
  select case when s.rest < 2 then 0 else 11 - s.rest end
  from (
    select sum(substr(p_digits, i, 1)::integer * p_weights[i]) % 11 as rest
    from generate_subscripts(p_weights, 1) i
  ) s;
$$;

-- Pix keys in their stored (normalized) form: CPF/CNPJ digits with valid check digits, "+55" phone,
-- lowercase e-mail up to 77 characters, or a random key (UUID).
create function private.is_valid_pix_key(p_type text, p_key text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select coalesce(case p_type
    when 'cpf' then
      case when p_key ~ '^[0-9]{11}$' and p_key !~ '^([0-9])\1{10}$' then
        private.mod11_check_digit(p_key, array[10, 9, 8, 7, 6, 5, 4, 3, 2]) = substr(p_key, 10, 1)::integer
        and private.mod11_check_digit(p_key, array[11, 10, 9, 8, 7, 6, 5, 4, 3, 2]) = substr(p_key, 11, 1)::integer
      else false end
    when 'cnpj' then
      case when p_key ~ '^[0-9]{14}$' and p_key !~ '^([0-9])\1{13}$' then
        private.mod11_check_digit(p_key, array[5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]) = substr(p_key, 13, 1)::integer
        and private.mod11_check_digit(p_key, array[6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]) = substr(p_key, 14, 1)::integer
      else false end
    when 'phone' then p_key ~ '^\+55[1-9][0-9]{9,10}$'
    when 'email' then char_length(p_key) <= 77
      and p_key ~ '^[a-z0-9._%+-]+@(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$'
    when 'random' then p_key ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  end, false);
$$;

-- 1 to 4 distinct fields from the catalog, in catalog order, with e-mail or phone.
create function private.is_valid_form_fields(p_fields jsonb)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select coalesce(
    jsonb_typeof(p_fields) = 'array'
    and jsonb_array_length(p_fields) between 1 and 4
    and not exists (
      select 1 from jsonb_array_elements(p_fields) e
      where jsonb_typeof(e) <> 'string' or (e #>> '{}') not in ('name', 'email', 'phone', 'message')
    )
    and (select array_agg(e #>> '{}' order by ord) from jsonb_array_elements(p_fields) with ordinality t(e, ord))
      = (select array_agg(f order by pos) from unnest(array['name', 'email', 'phone', 'message']) with ordinality c(f, pos) where p_fields ? f)
    and (p_fields ? 'email' or p_fields ? 'phone'),
    false);
$$;

-- A ready asset of the given kind that belongs to this page. When dimensions are given they must
-- be the asset's own, so a block cannot lie about the space an image takes.
create function private.is_ready_media(p_profile_id uuid, p_kind public.media_kind, p_media_id text, p_width jsonb, p_height jsonb)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.media_assets m
    where m.profile_id = p_profile_id
      and m.id::text = p_media_id
      and m.kind = p_kind
      and m.status = 'ready'
      and (p_width is null or (to_jsonb(m.width) = p_width and to_jsonb(m.height) = p_height))
  );
$$;

-- ---------------------------------------------------------------------------------------------
-- Draft validator (adds theme, avatar and the four block types to the Sprint 4 version)
-- ---------------------------------------------------------------------------------------------

create or replace function private.validate_profile_draft()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item jsonb;
  v_keys text[];
  v_expected text[];
  v_type text;
  v_valid boolean;
begin
  -- Legacy page-level social links (no longer written by the app, still validated).
  if not private.is_valid_social_links(new.social_links) then
    raise exception 'invalid social link' using errcode = 'LK040', detail = 'social_links';
  end if;

  if new.theme is not null and not private.is_valid_theme(new.theme) then
    raise exception 'invalid theme' using errcode = 'LK040', detail = 'theme';
  end if;

  if new.avatar_path is not null and not private.is_ready_media(new.id, 'avatar', new.avatar_path, null, null) then
    raise exception 'invalid avatar' using errcode = 'LK040', detail = 'avatar_path';
  end if;

  -- Serialized size cap (MAX_BLOCKS_BYTES); the 100-block cap is the profiles_blocks_shape check.
  if octet_length(new.blocks::text) > 65536 then
    raise exception 'draft too large' using errcode = 'LK040', detail = 'blocks';
  end if;

  for v_item in select value from jsonb_array_elements(new.blocks) loop
    if jsonb_typeof(v_item) <> 'object' then
      raise exception 'invalid block' using errcode = 'LK040', detail = 'blocks';
    end if;
    v_type := case when jsonb_typeof(v_item -> 'type') = 'string' then v_item ->> 'type' end;
    v_expected := case v_type
      when 'link' then array['id', 'title', 'type', 'url', 'visible']
      when 'text' then array['id', 'text', 'type', 'visible']
      when 'social' then array['id', 'items', 'type', 'visible']
      when 'whatsapp' then array['id', 'label', 'message', 'phone', 'type', 'visible']
      when 'divider' then array['id', 'type', 'visible']
      when 'image' then array['alt', 'decorative', 'height', 'id', 'mediaId', 'type', 'visible', 'width']
      when 'embed' then array['id', 'provider', 'ref', 'title', 'type', 'visible']
      when 'pix' then array['id', 'key', 'keyType', 'label', 'paymentUrl', 'type', 'visible']
      when 'form' then array['buttonLabel', 'consentRequired', 'consentText', 'fields', 'id', 'title', 'type', 'visible']
    end;
    select array_agg(k order by k collate "C") into v_keys from jsonb_object_keys(v_item) k;
    if v_expected is null
      or v_keys is distinct from v_expected
      or jsonb_typeof(v_item -> 'id') <> 'string'
      or (v_item ->> 'id') !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      or jsonb_typeof(v_item -> 'visible') <> 'boolean' then
      raise exception 'invalid block' using errcode = 'LK040', detail = 'blocks';
    end if;

    v_valid := case v_type
      when 'link' then
        jsonb_typeof(v_item -> 'title') = 'string'
        and jsonb_typeof(v_item -> 'url') = 'string'
        and private.is_valid_block_label(v_item ->> 'title', 80)
        and private.is_allowed_block_url(v_item ->> 'url')
      when 'text' then
        jsonb_typeof(v_item -> 'text') = 'string'
        and private.is_valid_block_text(v_item ->> 'text', 1, 1000)
      when 'social' then
        private.is_valid_social_links(v_item -> 'items')
      when 'whatsapp' then
        jsonb_typeof(v_item -> 'label') = 'string'
        and jsonb_typeof(v_item -> 'phone') = 'string'
        and jsonb_typeof(v_item -> 'message') = 'string'
        and private.is_valid_block_label(v_item ->> 'label', 80)
        and private.is_valid_whatsapp_phone(v_item ->> 'phone')
        and private.is_valid_block_text(v_item ->> 'message', 0, 500)
      when 'divider' then true
      when 'image' then
        jsonb_typeof(v_item -> 'mediaId') = 'string'
        and jsonb_typeof(v_item -> 'width') = 'number'
        and jsonb_typeof(v_item -> 'height') = 'number'
        and jsonb_typeof(v_item -> 'alt') = 'string'
        and jsonb_typeof(v_item -> 'decorative') = 'boolean'
        and case when v_item -> 'decorative' = 'true'::jsonb
          then v_item ->> 'alt' = ''
          else private.is_valid_block_label(v_item ->> 'alt', 200) end
        -- Same page, ready, an image, and the block's dimensions are the asset's.
        and private.is_ready_media(new.id, 'image', v_item ->> 'mediaId', v_item -> 'width', v_item -> 'height')
      when 'embed' then
        jsonb_typeof(v_item -> 'provider') = 'string'
        and jsonb_typeof(v_item -> 'ref') = 'string'
        and jsonb_typeof(v_item -> 'title') = 'string'
        and private.is_valid_embed_ref(v_item ->> 'provider', v_item ->> 'ref')
        and private.is_valid_block_label(v_item ->> 'title', 80)
      when 'pix' then
        jsonb_typeof(v_item -> 'label') = 'string'
        and jsonb_typeof(v_item -> 'keyType') = 'string'
        and jsonb_typeof(v_item -> 'key') = 'string'
        and jsonb_typeof(v_item -> 'paymentUrl') = 'string'
        and private.is_valid_block_label(v_item ->> 'label', 80)
        and private.is_valid_pix_key(v_item ->> 'keyType', v_item ->> 'key')
        and (v_item ->> 'paymentUrl' = ''
          or (v_item ->> 'paymentUrl' ~ '^https://' and private.is_allowed_block_url(v_item ->> 'paymentUrl')))
      when 'form' then
        jsonb_typeof(v_item -> 'title') = 'string'
        and jsonb_typeof(v_item -> 'buttonLabel') = 'string'
        and jsonb_typeof(v_item -> 'consentText') = 'string'
        and jsonb_typeof(v_item -> 'consentRequired') = 'boolean'
        and private.is_valid_block_label(v_item ->> 'title', 80)
        and private.is_valid_block_label(v_item ->> 'buttonLabel', 40)
        and private.is_valid_block_label(v_item ->> 'consentText', 300)
        and private.is_valid_form_fields(v_item -> 'fields')
    end;
    if not coalesce(v_valid, false) then
      raise exception 'invalid block' using errcode = 'LK040', detail = 'blocks';
    end if;
  end loop;

  if (select count(*) from jsonb_array_elements(new.blocks))
    <> (select count(distinct e ->> 'id') from jsonb_array_elements(new.blocks) e) then
    raise exception 'duplicate block id' using errcode = 'LK040', detail = 'blocks';
  end if;

  return new;
end;
$$;

-- The validator now also guards the theme and the avatar.
drop trigger profiles_30_validate_draft on public.profiles;
create trigger profiles_30_validate_draft
before insert or update of social_links, blocks, theme, avatar_path on public.profiles
for each row execute function private.validate_profile_draft();

create or replace function private.bump_draft_revision()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.title is distinct from old.title
    or new.bio is distinct from old.bio
    or new.avatar_path is distinct from old.avatar_path
    or new.social_links is distinct from old.social_links
    or new.blocks is distinct from old.blocks
    or new.theme is distinct from old.theme then
    new.draft_revision := old.draft_revision + 1;
  else
    new.draft_revision := old.draft_revision;
  end if;
  return new;
end;
$$;

-- Every role that edits the draft also edits its theme and avatar (same compare-and-swap save).
grant update (theme, avatar_path) on public.profiles to authenticated;

-- ---------------------------------------------------------------------------------------------
-- Snapshot document: still schema version 2, additive (mirror of modules/publishing/document.ts)
-- ---------------------------------------------------------------------------------------------

create or replace function private.published_block(p_block jsonb)
returns jsonb
language sql
immutable
set search_path = ''
as $$
  select case p_block ->> 'type'
    when 'link' then jsonb_build_object('id', p_block ->> 'id', 'type', 'link', 'title', p_block ->> 'title', 'url', p_block ->> 'url')
    when 'text' then jsonb_build_object('id', p_block ->> 'id', 'type', 'text', 'text', p_block ->> 'text')
    when 'social' then jsonb_build_object('id', p_block ->> 'id', 'type', 'social', 'items', p_block -> 'items')
    when 'whatsapp' then jsonb_build_object('id', p_block ->> 'id', 'type', 'whatsapp', 'label', p_block ->> 'label', 'phone', p_block ->> 'phone', 'message', p_block ->> 'message')
    when 'divider' then jsonb_build_object('id', p_block ->> 'id', 'type', 'divider')
    when 'image' then jsonb_build_object('id', p_block ->> 'id', 'type', 'image', 'mediaId', p_block ->> 'mediaId', 'width', p_block -> 'width', 'height', p_block -> 'height', 'alt', p_block ->> 'alt')
    when 'embed' then jsonb_build_object('id', p_block ->> 'id', 'type', 'embed', 'provider', p_block ->> 'provider', 'ref', p_block ->> 'ref', 'title', p_block ->> 'title')
    when 'pix' then jsonb_build_object('id', p_block ->> 'id', 'type', 'pix', 'label', p_block ->> 'label', 'keyType', p_block ->> 'keyType', 'key', p_block ->> 'key', 'paymentUrl', p_block ->> 'paymentUrl')
    when 'form' then jsonb_build_object('id', p_block ->> 'id', 'type', 'form', 'title', p_block ->> 'title', 'fields', p_block -> 'fields', 'buttonLabel', p_block ->> 'buttonLabel', 'consentText', p_block ->> 'consentText', 'consentRequired', p_block -> 'consentRequired')
  end;
$$;

-- `theme` is present only when the page has one, so a page without a theme publishes exactly the
-- document it published before this migration.
create or replace function private.build_publication_document(p_profile public.profiles)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'schemaVersion', 2,
    'title', p_profile.title,
    'bio', p_profile.bio,
    'avatarPath', p_profile.avatar_path,
    'blocks', coalesce((
      select jsonb_agg(private.published_block(b) order by ord)
      from jsonb_array_elements(p_profile.blocks) with ordinality as t(b, ord)
      where (b ->> 'visible')::boolean
        and private.published_block(b) is not null
        and not (b ->> 'type' = 'social' and jsonb_array_length(b -> 'items') = 0)
    ), '[]'::jsonb)
  ) || case when p_profile.theme is null then '{}'::jsonb else jsonb_build_object('theme', p_profile.theme) end;
$$;

-- ---------------------------------------------------------------------------------------------
-- Form leads
-- ---------------------------------------------------------------------------------------------

-- How long a lead is kept (provisional). Expired leads are hidden by RLS at once and deleted on the
-- next submission to the page or by the purge job (Sprint 9).
create function private.lead_retention()
returns interval
language sql
immutable
set search_path = ''
as $$ select interval '90 days' $$;

create table public.form_leads (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  profile_id uuid not null references public.profiles (id) on delete cascade,
  -- Id of the form block in the publication the visitor saw.
  block_id text not null check (char_length(block_id) between 1 and 64),
  publication_version integer not null,
  name text check (name is null or char_length(name) between 1 and 100),
  email text check (email is null or char_length(email) between 3 and 254),
  phone text check (phone is null or phone ~ '^\+?[0-9]{8,15}$'),
  message text check (message is null or char_length(message) between 1 and 1000),
  consent_given boolean not null,
  consent_required boolean not null,
  -- The exact text the visitor saw, and its version (MD5 of the text).
  consent_text text not null check (char_length(consent_text) between 1 and 300),
  consent_version text not null check (consent_version ~ '^[0-9a-f]{32}$'),
  consented_at timestamptz,
  -- Same form and same content: used to store a retried submission only once.
  dedupe_key text not null check (dedupe_key ~ '^[0-9a-f]{32}$'),
  created_at timestamptz not null default now(),
  purge_after timestamptz not null,
  constraint form_leads_contact check (email is not null or phone is not null),
  constraint form_leads_consent_timestamp check (consent_given = (consented_at is not null)),
  constraint form_leads_required_consent check (not consent_required or consent_given)
);

create index form_leads_profile_created_idx on public.form_leads (profile_id, created_at desc);
create index form_leads_workspace_idx on public.form_leads (workspace_id);
create index form_leads_purge_after_idx on public.form_leads (purge_after);
create index form_leads_dedupe_idx on public.form_leads (profile_id, dedupe_key, created_at desc);

comment on table public.form_leads is
  'Personal data typed by visitors in a form block (ADR 0010). The page owner is the controller; the product is the operator. Never contains IP addresses. Retention: private.lead_retention() (90 days, provisional) through purge_after.';

-- Accepted submissions per visitor hash, for the rate limit only. The hash is an HMAC of the IP
-- keyed by a server secret and the day (never the raw address); rows older than a day are deleted.
create table public.form_submission_hits (
  id bigint generated always as identity primary key,
  profile_id uuid not null references public.profiles (id) on delete cascade,
  client_hash text not null check (client_hash ~ '^([0-9a-f]{32}|direct)$'),
  created_at timestamptz not null default now()
);

create index form_submission_hits_profile_created_idx on public.form_submission_hits (profile_id, created_at desc);
create index form_submission_hits_client_idx on public.form_submission_hits (profile_id, client_hash, created_at desc);

comment on table public.form_submission_hits is
  'Rate-limit counters for form submissions (ADR 0010): page + salted daily hash of the visitor address. No raw IP. Rows are deleted after 24 hours by submit_form_lead.';

-- The only write path for visitors. Validates against the form in the LIVE publication, so a form
-- that was removed or never published accepts nothing. Answers with a status and nothing else:
--   ok               stored (or a retry of something already stored, or a filled honeypot)
--   invalid          a field is missing or malformed
--   consent_required the form requires consent and it was not given
--   rate_limited     too many submissions from this visitor or to this page
--   unavailable      no such published form at this address
create function public.submit_form_lead(
  p_slug text,
  p_block_id text,
  p_fields jsonb,
  p_consent boolean default false,
  p_honeypot text default '',
  p_client_hash text default null
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_slug text := private.normalize_slug(coalesce(p_slug, ''));
  v_profile public.profiles;
  v_document jsonb;
  v_version integer;
  v_form jsonb;
  v_field text;
  v_value text;
  v_name text;
  v_email text;
  v_phone text;
  v_message text;
  v_consent boolean := coalesce(p_consent, false);
  v_client text;
  v_dedupe text;
begin
  -- Hidden field real visitors never fill. Automated posts get the same answer as a real one.
  if btrim(coalesce(p_honeypot, '')) <> '' then
    return 'ok';
  end if;
  if not private.slug_is_well_formed(v_slug) or p_block_id is null then
    return 'unavailable';
  end if;
  if p_fields is null or jsonb_typeof(p_fields) <> 'object' or octet_length(p_fields::text) > 4096 then
    return 'invalid';
  end if;

  select p.* into v_profile
  from public.profiles p
  join public.workspaces w on w.id = p.workspace_id
  where p.slug = v_slug
    and p.deleted_at is null
    and p.live_publication_id is not null
    and w.deleted_at is null
    and w.status = 'active';
  if not found then
    return 'unavailable';
  end if;

  select pp.document, pp.version into v_document, v_version
  from public.profile_publications pp where pp.id = v_profile.live_publication_id;
  select b into v_form
  from jsonb_array_elements(case when jsonb_typeof(v_document -> 'blocks') = 'array' then v_document -> 'blocks' else '[]'::jsonb end) b
  where b ->> 'id' = p_block_id and b ->> 'type' = 'form'
  limit 1;
  if v_form is null or not private.is_valid_form_fields(v_form -> 'fields') then
    return 'unavailable';
  end if;

  -- Only the fields of the published form are read; anything else in the request is ignored.
  for v_field in select f from unnest(array['name', 'email', 'phone', 'message']) f where v_form -> 'fields' ? f loop
    v_value := case when jsonb_typeof(p_fields -> v_field) = 'string' then p_fields ->> v_field else '' end;
    if v_field = 'message' then
      v_value := btrim(regexp_replace(v_value, E'\r\n?', E'\n', 'g'), E' \t\n');
      if char_length(v_value) > 1000 or replace(v_value, E'\n', '') ~ '[[:cntrl:]]' then
        return 'invalid';
      end if;
      v_message := nullif(v_value, '');
    else
      v_value := regexp_replace(btrim(v_value, E' \t\n\r'), '\s+', ' ', 'g');
      if v_value = '' or v_value ~ '[[:cntrl:]]' then
        return 'invalid';
      end if;
      if v_field = 'name' then
        if char_length(v_value) > 100 then return 'invalid'; end if;
        v_name := v_value;
      elsif v_field = 'email' then
        v_value := lower(v_value);
        if char_length(v_value) > 254 or v_value !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then return 'invalid'; end if;
        v_email := v_value;
      else
        if char_length(v_value) > 20 or v_value !~ '^\+?[0-9[:space:]().-]+$' then return 'invalid'; end if;
        v_phone := case when v_value like '+%' then '+' else '' end || regexp_replace(v_value, '[^0-9]', '', 'g');
        if v_phone !~ '^\+?[0-9]{8,15}$' then return 'invalid'; end if;
      end if;
    end if;
  end loop;

  if coalesce((v_form ->> 'consentRequired')::boolean, true) and not v_consent then
    return 'consent_required';
  end if;

  -- One submission at a time per page, so the counters below cannot be raced.
  perform pg_advisory_xact_lock(hashtextextended('form_lead:' || v_profile.id::text, 0));

  delete from public.form_submission_hits h where h.profile_id = v_profile.id and h.created_at < now() - interval '1 day';
  delete from public.form_leads l where l.profile_id = v_profile.id and l.purge_after < now();

  -- Retry safety: the same content to the same form within 10 minutes is stored once.
  v_dedupe := md5(v_profile.id::text || ':' || p_block_id || ':' || coalesce(v_name, '') || E'\x1f' || coalesce(v_email, '') || E'\x1f' || coalesce(v_phone, '') || E'\x1f' || coalesce(v_message, ''));
  if exists (
    select 1 from public.form_leads l
    where l.profile_id = v_profile.id and l.dedupe_key = v_dedupe and l.created_at > now() - interval '10 minutes'
  ) then
    return 'ok';
  end if;

  -- A caller without a hash from the application (a direct API call) shares one bucket.
  v_client := case when p_client_hash ~ '^[0-9a-f]{32}$' then p_client_hash else 'direct' end;
  if (select count(*) from public.form_submission_hits h
      where h.profile_id = v_profile.id and h.client_hash = v_client and h.created_at > now() - interval '10 minutes') >= 5
    or (select count(*) from public.form_submission_hits h
        where h.profile_id = v_profile.id and h.created_at > now() - interval '1 hour') >= 60 then
    return 'rate_limited';
  end if;

  insert into public.form_submission_hits (profile_id, client_hash) values (v_profile.id, v_client);
  insert into public.form_leads (
    workspace_id, profile_id, block_id, publication_version, name, email, phone, message,
    consent_given, consent_required, consent_text, consent_version, consented_at, dedupe_key, purge_after)
  values (
    v_profile.workspace_id, v_profile.id, p_block_id, v_version, v_name, v_email, v_phone, v_message,
    v_consent, coalesce((v_form ->> 'consentRequired')::boolean, true), v_form ->> 'consentText', md5(v_form ->> 'consentText'),
    case when v_consent then now() end, v_dedupe, now() + private.lead_retention());
  return 'ok';
end;
$$;

-- Shared authorization for owner-side lead commands: owners and admins of a writable workspace.
create function private.authorize_lead_admin(p_workspace_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role public.workspace_role;
begin
  if (select auth.uid()) is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  v_role := private.workspace_role(p_workspace_id);
  if v_role is null then
    raise exception 'not found' using errcode = 'P0002';
  end if;
  if not private.workspace_is_writable(p_workspace_id) then
    raise exception 'workspace does not accept changes' using errcode = '42501';
  end if;
  -- Matrix: leads.delete and leads.export = owner, admin (modules/identity/permissions.ts).
  if v_role not in ('owner', 'admin') then
    raise exception 'only owners and admins manage leads' using errcode = '42501';
  end if;
end;
$$;

create function public.delete_form_lead(p_lead_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_lead public.form_leads;
begin
  if (select auth.uid()) is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  select l.* into v_lead from public.form_leads l where l.id = p_lead_id for update;
  if not found or private.workspace_role(v_lead.workspace_id) is null then
    raise exception 'lead not found' using errcode = 'P0002';
  end if;
  perform private.authorize_lead_admin(v_lead.workspace_id);

  delete from public.form_leads where id = p_lead_id;
  -- The trail records that a deletion happened, never the lead's content.
  perform private.write_audit_event(v_lead.workspace_id, 'lead.deleted', 'profile', v_lead.profile_id, jsonb_build_object('count', 1));
end;
$$;

-- Called by the application right before it hands a CSV to the person.
create function public.record_lead_export(p_profile_id uuid, p_count integer)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_workspace_id uuid;
begin
  if (select auth.uid()) is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;
  select p.workspace_id into v_workspace_id from public.profiles p where p.id = p_profile_id and p.deleted_at is null;
  if not found or private.workspace_role(v_workspace_id) is null then
    raise exception 'profile not found' using errcode = 'P0002';
  end if;
  perform private.authorize_lead_admin(v_workspace_id);
  perform private.write_audit_event(v_workspace_id, 'lead.exported', 'profile', p_profile_id,
    jsonb_build_object('count', greatest(0, coalesce(p_count, 0))));
end;
$$;

alter table public.form_leads enable row level security;
alter table public.form_submission_hits enable row level security;
revoke all on public.form_leads, public.form_submission_hits from public, anon, authenticated, service_role;

-- Members read the leads of live pages in their workspaces while they are within retention.
-- Visitors (anon) have no privilege at all; writes go through submit_form_lead and delete_form_lead.
grant select on public.form_leads to authenticated;

create policy form_leads_select_member on public.form_leads
for select to authenticated
using (
  workspace_id in (select private.member_workspace_ids())
  and profile_id in (select p.id from public.profiles p)
  and purge_after > now()
);

-- form_submission_hits: server-only (no policies).
grant select, delete on public.form_leads, public.form_submission_hits to service_role;

-- ---------------------------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------------------------

revoke all on all functions in schema private from public, anon, authenticated;
grant execute on function
  private.member_workspace_ids(),
  private.writable_workspace_ids(public.workspace_role[]),
  private.workspace_ids_with_role(public.workspace_role[])
to authenticated;

revoke all on function
  public.register_media_asset(uuid, uuid, public.media_kind, integer, integer, jsonb, text),
  public.activate_media_asset(uuid, text),
  public.fail_media_asset(uuid),
  public.workspace_storage_usage(uuid),
  public.claim_media_cleanup(integer),
  public.finish_media_cleanup(uuid[]),
  public.submit_form_lead(text, text, jsonb, boolean, text, text),
  public.delete_form_lead(uuid),
  public.record_lead_export(uuid, integer)
from public, anon, authenticated, service_role;

grant execute on function
  public.register_media_asset(uuid, uuid, public.media_kind, integer, integer, jsonb, text),
  public.activate_media_asset(uuid, text),
  public.fail_media_asset(uuid),
  public.workspace_storage_usage(uuid),
  public.delete_form_lead(uuid),
  public.record_lead_export(uuid, integer)
to authenticated;

-- Visitors submit forms; signed-in people may too (an owner testing their own page).
grant execute on function public.submit_form_lead(text, text, jsonb, boolean, text, text) to anon, authenticated;

-- Cleanup is an administrative job, never a user action.
grant execute on function public.claim_media_cleanup(integer), public.finish_media_cleanup(uuid[]) to service_role;

comment on table public.profiles is
  'Link page (UI: "página"). Columns title, bio, avatar_path, theme, social_links and blocks are the draft; the public page is the snapshot in live_publication_id. Soft delete: deleted_at + purge_after (30 days); the slug moves to slug_history.';
